### ISSUE TITLE
No Longer working with Newest Chrome Version

### ISSUE THREAD

**Issue by seff907** [jjjchens235/bing-rewards#100]
Hi,

This seems to be no longer working after my installation of chrome has updated to version 95.0.4638.54. I have downloaded the newest code but I still get the issue.

Any help would be greatly appreciated. I really enjoy using this tool.

> Command line options selected:
> search_type=remaining, headless=True, email=None
> 
> ['Thu, Oct 21 2021 06:03PM', 'Failed Edge Search, Web Search, Mobile Search, Offers']
> 
>         You selected remaining
> 
> > Starting Edge search
> 
> DevTools listening on ws://127.0.0.1:56252/devtools/browser/e3ba964f-8305-4015-b26e-fc509570f0bd
> Downloading chromedriver version: 93.0.4577.63
> 
> DevTools listening on ws://127.0.0.1:52972/devtools/browser/2ecbe485-d4b0-44df-96ea-107bf52eaaff
> Downloading chromedriver version: 92.0.4515.107
> 
> DevTools listening on ws://127.0.0.1:49541/devtools/browser/a6f4878e-b569-4c85-8ade-0415a8258c16
> Traceback (most recent call last):
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\src\driver.py", line 131, in get_driver
>     driver = webdriver.Chrome(path, options=options)
>   File "C:\Users\Jeff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 76, in __init__
>     RemoteWebDriver.__init__(
>   File "C:\Users\Jeff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
>     self.start_session(capabilities, browser_profile)
>   File "C:\Users\Jeff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
>     response = self.execute(Command.NEW_SESSION, parameters)
>   File "C:\Users\Jeff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Jeff\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 92
> Current browser version is 95.0.4638.54 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 161, in <module>
>     __main()
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\BingRewards.py", line 73, in __main
>     rewards.complete_all(hist_log.get_search_hist())
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1278, in complete_all
>     driver = self.__complete_edge_search()
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 1076, in __complete_edge_search
>     driver = Driver.get_driver(
>   File "C:\Users\Jeff\Desktop\bing-rewards-master\BingRewards\src\driver.py", line 136, in get_driver
>     raise SessionNotCreatedException(f'Tried downloading the {try_count} most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.')
> selenium.common.exceptions.SessionNotCreatedException: Message: Tried downloading the 3 most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.

**Comment by jjjchens235** [comment]
Updated, let me know if this fixes your issue.

**Comment by seff907** [comment]
Thank you, this fixed it!
