### ISSUE TITLE
Evading navigator.webdriver

### ISSUE THREAD

**Issue by samhenrigold** [jjjchens235/bing-rewards#105]
Unsure if Bing checks for web drivers this way to ban users but is there any way to obscure Selenium's patterns? I'm not super well versed in Python otherwise I'd add something myself but just wanted to poll the maintainers about this.

Thanks!

**Comment by jjjchens235** [comment]
Something like [this](https://github.com/jjjchens235/bing-rewards/issues/78#issuecomment-961697890) ? Planning to implement that soon.

**Comment by jjjchens235** [comment]
Closing here, will implement fix in Issue #78
