### ISSUE TITLE
Passwordless accounts not working properly

### ISSUE THREAD

**Issue by asamson23** [jjjchens235/bing-rewards#108]
The program doesn't work in headless mode, and it doesn't wait for the prompt before the script throws exceptions

**Comment by asamson23** [comment]
The script also always forgets 2FA authorisations, making me need to confirm the request quickly on my phone

**Comment by jjjchens235** [comment]
Hi, 2FA is not currently supported.

Dup of t[his,](https://github.com/jjjchens235/bing-rewards/issues/58) so closing
