### ISSUE TITLE
Disable region check

### ISSUE THREAD

**Issue by icanotc** [jjjchens235/bing-rewards#109]
error message:
```
RuntimeError: Logged in, but user not located in one of these valid markets: ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR', 'mkt=ES-ES', 'mkt=EN-AU'].
```

when I do a no headless mode with the script, the end of the URL would say ZH-CN as the market, but I can do all the ms rewards stuff just fine manually. 

I live in the US and set the language & region set to English and US, but the URL in chrome is still showing up as ZH-CN, so I feel like the best way to solve this is just to disable the region check completely.

**Comment by jjjchens235** [comment]
Hi - I don't want to remove this check as it is a legitimate check for certain markets where this script will not work.

I think the simplest fix would be for me to append to the list `mkt=ZH-CN`, any thoughts?

**Comment by jjjchens235** [comment]
Actually, can you update the code yourself to the following and let me know the result?
Inside rewards.py, you need to update the `VALID_MARKETS` variable to:
        VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR', 'mkt=ES-ES', 'mkt=EN-AU','mkt=ZH-CN' ]

**Comment by icanotc** [comment]
I feel like that would be a really hacky way, since my market is not actually ZH-CN, the script would work just fine. but if someone is actually in the ZH-CN market, the script would just malfunction. (try switching the language to Chinese, all the rewards stuff are gone) 

Also, after I added the ZH-CN market, it worked out pretty well.

**Comment by jjjchens235** [comment]
I'll add the CN market in the next push. If someone whose market is actually CN asks why the script isn't working for them, I'll remove it then.

**Comment by icanotc** [comment]
Thanks, but I don't see a push that adds the CN market, can you make sure that you pushed the commit for that?

**Comment by jjjchens235** [comment]
It's here: https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L145
