### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by icanotc** [jjjchens235/bing-rewards#110]
This script would default to download the x86 chrome driver each time, which then will run chrome in x86 mode with rosetta. 

fix:

add a check to see if the platform is m1, if it is, download the m1 version of the chrome driver

here is the output for the platform module
```
>>> import platform
>>> platform.system()
'Darwin'
>>> platform.processor()
'arm'
>>> platform.platform()
'macOS-12.0.1-arm64-arm-64bit'
>>> platform.machine()
'arm64'
>>> platform.version()
'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101'
>>> platform.uname()
uname_result(system='Darwin', node='maple.local', release='21.1.0', version='Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101', machine='arm64')
>>>
```
and to let the script download the right chromedriver binary, I added these few lines before where it downloads the normal binary for x86
```
elif system == "Darwin" and platform.processor() == "arm":
            url = "https://chromedriver.storage.googleapis.com/{}/chromedriver_mac64_m1.zip".format(
                latest_version
            )
```
 not a python dev here, so that might not the best solution.

**Comment by jjjchens235** [comment]
thanks your code helps a lot, I'll take a look this weekend time permitting

**Comment by jjjchens235** [comment]
Implemented, lmk if there are any issues. Thanks again for the code- it was useful.

**Comment by icanotc** [comment]
Sounds great, ill try the new code and see if they have any problems.
