### ISSUE TITLE
[-nhl] "Failed to create data directory"

### ISSUE THREAD

**Issue by jasperan** [jjjchens235/bing-rewards#112]
Whenever I try to execute the code in non-headless mode, I get this new error from a Chrome prompt:

"Failed to create data directory"
Google Chrome cannot read and write to its data directory:
stored_browser_data

I think it's related to your cookies implementation to save the state of the chromedriver

**Comment by jasperan** [comment]
@AndrewChqng you can checkout to a previous commit where it worked as a temporary fix

**Comment by jjjchens235** [comment]
dup #111
