### ISSUE TITLE
Failed to create data directory

### ISSUE THREAD

**Issue by FouSpeed** [jjjchens235/bing-rewards#115]
When executing BingRewards.py without options `-e` and `-p`, Chrome sends an error message : 
```
Failed to create data directory
Google Chrome cannot read and write to its data directory:
stored_browser_data
```
This message doesn't appear when launching command with `-e` and `-p` options.

![image](https://user-images.githubusercontent.com/65353789/142736646-de72466a-f44a-466b-bf43-866c661cb813.png)

**Comment by DavidARoberts** [comment]
I found that running the command prompt or my scheduled task as Administrator solved this issue.

**Comment by jjjchens235** [comment]
dup of #111
