### ISSUE TITLE
Dev branch - Chromedriver updates to beta version

### ISSUE THREAD

**Issue by DavidARoberts** [jjjchens235/bing-rewards#120]
I was on a much older version of chrome so I updated to 96. I noticed that the code is attempting to grab the second driver version but for me it was grabbing 97 which is in beta. Maybe something like this can be implemented to target a specific release.

import subprocess
output = subprocess.check_output(
    r'wmic datafile where name="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" get Version /value',
    shell=True
)
print(output.decode('utf-8').strip())

----Output-----
Version=79.0.3945.117

**Comment by jjjchens235** [comment]
This is fixed.
