### ISSUE TITLE
For the level 1 account

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#121]
Add to

 if is_edge:
            search_types = ['EDGE']
        elif device == Driver.WEB_DEVICE:
            **search_types = ['PC']**
        elif device == Driver.MOBILE_DEVICE:
            search_types = ['MÓVILES', 'MOBILE', 'MOBILI']

 if is_edge:
            search_types = ['EDGE']
        elif device == Driver.WEB_DEVICE:
            **search_types = ['PC', 'SEARCH']**
        elif device == Driver.MOBILE_DEVICE:
            search_types = ['MÓVILES', 'MOBILE', 'MOBILI']

**Comment by jjjchens235** [comment]
this issue was already mentioned in a separate PR
