### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#123]
>               >>> Starting quiz
>                   <<< Could not detect quiz overlay
>               >>> Starting quiz2 (no overlay)
> Traceback (most recent call last):
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/BingRewards.py", line 164, in <module>
>     __main()
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/BingRewards.py", line 76, in __main
>     rewards.complete_all(hist_log.get_search_hist())
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/src/rewards.py", line 1268, in complete_all
>     self.__complete_offers(driver)
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/src/rewards.py", line 1154, in __complete_offers
>     self.completion.offers = self.__offers(driver)
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/src/rewards.py", line 1047, in __offers
>     c = self.__click_offer(
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/src/rewards.py", line 958, in __click_offer
>     completed = self.__quiz2(driver)
>   File "/Users/affoghiamoci/Documents/Rewards/Michele/BingRewards/src/rewards.py", line 798, in __quiz2
>     for x in re.match("\((\d+) of (\d+)\)", progress).groups()
> AttributeError: 'NoneType' object has no attribute 'groups'

Every try i have this problem, any fix?

**Comment by jjjchens235** [comment]
This is an issue with non-English site. This should be an easy fix, but going forward, I do not guarantee that I will fix non-English issues as I cannot test them myself.

Please update these lines of [code](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L795-L797) with the following:
``` py
current_progress, complete_progress = [
    int(x)
    for x in re.match("\((\d+)[a-zA-Z ]+(\d+)\)", progress).groups()
]
```

If this fixes the issue, I can integrate the change to the code-base.
If it does not fix the issue, please let me know how the UI reports your quiz progress, in the English version it reports it with this format: `(5 of 10)`

**Comment by Affoghiamoci** [comment]
yes it fix that! thanks you
