### ISSUE TITLE
Message: Tried downloading the 3 most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser

### ISSUE THREAD

**Issue by Aholicknight** [jjjchens235/bing-rewards#124]
```
Traceback (most recent call last):
  File "C:\BingRewards\bing-rewards-master\bing-rewards-master\BingRewards\BingRewards.py", line 164, in <module>
    __main()
  File "C:\BingRewards\bing-rewards-master\bing-rewards-master\BingRewards\BingRewards.py", line 145, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\BingRewards\bing-rewards-master\bing-rewards-master\BingRewards\src\rewards.py", line 1265, in complete_all
    driver = self.__complete_edge_search()
  File "C:\BingRewards\bing-rewards-master\bing-rewards-master\BingRewards\src\rewards.py", line 1063, in __complete_edge_search
    driver = Driver.get_driver(
  File "C:\BingRewards\bing-rewards-master\bing-rewards-master\BingRewards\src\driver.py", line 148, in get_driver
    raise SessionNotCreatedException(f'Tried downloading the {dl_try_count} most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.')
selenium.common.exceptions.SessionNotCreatedException: Message: Tried downloading the 3 most recent chromedrivers. None match your Chrome browswer version. Aborting now, please update your chrome browser.
```

I downloaded the latest chromedriver (97) from https://chromedriver.chromium.org/downloads and dropped it into the driver's folder. When I run the python file, nothing happens, and it tries to download chromedriver two times before failing.
![image](https://user-images.githubusercontent.com/7843719/143058655-5901a0ea-7ce8-416c-8a0d-5b47dc37dff9.png)

Is there any fix for this? Thank you.

**Comment by Affoghiamoci** [comment]
try to not download and leave the folder empty, the script load the right versione of chromedriver

**Comment by jjjchens235** [comment]
I agree with @Affoghiamoci , there should be no reason to have to download chromedriver manually.

Curious, in your **actual** chrome browser, what version does it say you're on?

**Comment by Aholicknight** [comment]
@jjjchens235 the version on my chrome is 96.0.4664.45. I am trying what @Affoghiamoci says now.

**Comment by Aholicknight** [comment]
Same problem that happened before. I deleted the exe just like what @Affoghiamoci said and it still somehow installs an older version of the driver. I uninstalled the driver many times, even reinstalled this repo and replaced all the files, and that still does not work. 
![image](https://user-images.githubusercontent.com/7843719/143174434-0cd49356-7b18-4764-86a7-ed2b90e72e8b.png)

It shows the same error as before and takes forever to see if it will work or not.

**Comment by jjjchens235** [comment]
#### Brief explanation of what the code does
The program installs the latest version of chromedriver. If that isn't compatible with your browser, it tries the 2nd latest version etc.

In the 2nd attempt, it downloaded the correct version, v96.0 which matches your actual browser. The program should proceed here, but when the driver browser is opened, it crashes, so it proceeds to download v95.0.

#### Potential fix
Try manually downloading the driver like you were doing. However, please download v96 to match your browser, link [here](https://chromedriver.storage.googleapis.com/index.html?path=96.0.4664.45/).

Once downloaded, you need to do the following
1. unzip the file
2. move it to `drivers/` sub-folder.
3. Run with no cookies `python BingRewards.py -nc -nhl`

Hopefully, this works. 
If the program tries downloading another version, it means that the original version you downloaded is not compatible with your browser.

**Comment by jjjchens235** [comment]
I think the error msg is a red herring as someone encountered similar behavior as you but posted the full log.

I'm closing this thread and further discussion can happen here:
https://github.com/jjjchens235/bing-rewards/issues/126#issuecomment-979361621
