### ISSUE TITLE
User not located in VALID_MARKETS

### ISSUE THREAD

**Issue by alfredus00** [jjjchens235/bing-rewards#125]
Hello, when i run the script using -nhl or without, it says that user is not located in VALID_MARKETS

I'm actually running the script inside a VPS that has Ubuntu OS located in Germany

My python version is 3.5.2, and i have all the requirements.txt

1. Run using non-headless mode: `python BingRewards -nhl`
I posted the screenshot of my console running non-headless mode [Here on imgur](https://imgur.com/a/JTJGa40)

I hope you can help me
thanks
p.s sorry for bad English

**Comment by Affoghiamoci** [comment]
add at 
#VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR', 'mkt=ES-ES', 'mkt=IT-IT']
mkt=DE-DE (i suppose)

and at 
# elif device == Driver.MOBILE_DEVICE:
            #search_types = ['MÓVILES', 'MOBILE', 'MOBILI']

'MOBILE' in you language

**Comment by jjjchens235** [comment]
You'll have to do two things:
1. Upgrade to python 3.6 else you will run into syntax errors
2. Follow @Affoghiamoci  suggestion

**Comment by alfredus00** [comment]
thank you so much @Affoghiamoci @jjjchens235  😍
