### ISSUE TITLE
whilst running with both -nc and -nhl. -nhl doesnt work!

### ISSUE THREAD

**Issue by Mottledkarma517** [jjjchens235/bing-rewards#127]
There are no error, it just runs like I never put -nhl.
By the way, I'm using dev version (I have errors when not running it in dev)

**Comment by jjjchens235** [comment]
I ran `python BingRewards.py -nc -nhl` and the behavior worked as expected.

Master and dev are the same now FYI.

**Comment by Mottledkarma517** [comment]
Thanks for the info!
