### ISSUE TITLE
Use Microsoft edge driver ????

### ISSUE THREAD

**Issue by hosein-hub** [jjjchens235/bing-rewards#128]
Hi
First I wanted to thank you for this good script you wrote / developed.
Can you use the Microsoft Edge driver?
How many times have I seen suggestions come to the dashboard with this text: ‌ "Get 2x daily search points in Microsoft Edge for 7 days. Valid 11/15-12/15"
If you can let user select the driver to use, it will be very good (during the initial installation, ask the user what driver he wants to use)
Thanks again for you and your program.

**Comment by jjjchens235** [comment]
Thanks for your kind words. 

This feature request is on my list, per #82
