### ISSUE TITLE
Not an issue, but maybe help in 'streamlining' your code

### ISSUE THREAD

**Issue by ShoGinn** [jjjchens235/bing-rewards#130]
Check out this code. He uses the Microsoft javascript dashboard to pull most of the info instead of relying on internal html.

Also has solvers for quizzes etc.

https://github.com/ddday/micro

**Comment by sensboston** [comment]
@ShoGinn, have you tried that script? It was updated 6 months ago and I don't think it still working with all MS changes...

**Comment by sensboston** [comment]
Interesting, I should try.

**Comment by jjjchens235** [comment]
Thanks for sharing, this code is clean.

You're referring to this [code](https://github.com/ddday/micro/blob/main/ms_rewards_farmer.py#L463) in particular?

I have no knowledge of JS whatsoever, for example this code I don't know what it's doing. Do you mind providing some context, I'm curious now.
```js
dashboard = findBetween(browser.find_element_by_xpath('/html/body').get_attribute('innerHTML'), "var dashboard = ", ";\n        appDataModule.constant(\"prefetchedDashboard\", dashboard);")

```

**Comment by ShoGinn** [comment]
This is the part that I was referencing. I am not sure why they chose to do it in that exact way. 

'''

try:
            self.dash_data = self.driver.execute_script("return dashboard")
        except JavascriptException:
            html_source = self.driver.get_attribute("/html/body", "innerHTML")
            dashboard = re.search(
                r"var dashboard =\s(.*?)\;"
                r"\n\s+appDataModule.constant\(\"prefetchedDashboard\", dashboard\);",
                html_source,
            )
            if dashboard:
                self.dash_data = json.loads(dashboard.group(1))
'''

My implementation

**Comment by jjjchens235** [comment]
Holy shit this dictionary has everything!!!! Awesome tip, this can definitely help streamline the code.

**Comment by JartanFTW** [comment]
How's the progress on this going? Very excited to see the update.

**Comment by jjjchens235** [comment]
Hey Jartan - 
This is already implemented, but if you find additional use cases for it, by all means, let me know. It doesn't change anything for the end user.

The program has access to the dashboard via this [method](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L209). This method is called in various parts of the program.

**Comment by JartanFTW** [comment]
Ah nice, didn't realize this was implemented already. More-so just interested in the improvement of the program in general.
