### ISSUE TITLE
Security Info Change/Login Issue

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#134]
I had to change my email address so I requested a change that takes 30 days for MS to replace. However, after logging in I get a page titled "Did you request security info change?" and that messes up the login. One more thing to add to the logging process?

![capture-20211213-152534](https://user-images.githubusercontent.com/52211825/145884157-ad56bba5-c0c7-4f0c-a889-cee58d1ef691.png)

**Comment by jjjchens235** [comment]
Thanks for calling this out. This seems like a pretty niche corner case that is annoying to reproduce, so probably not gonna add anything on my end. More than happy to merge a PR though.
