### ISSUE TITLE
Create config file by running python setup.py

### ISSUE THREAD

**Issue by Powered87** [jjjchens235/bing-rewards#137]
Hi there,

Minor detail, but when I create the config file by running python setup.py in PS or CMD, it won't let me enter anything after hashing the user name (so I can't enter the password).

**Comment by sensboston** [comment]
OMG, how many accounts do you have, thousands? And how do you create so many accounts automatically?

**Comment by jjjchens235** [comment]
Hi OP- I don't have a Windows computer anymore, but if memory serves correctly, you just need to type your password and while it looks like nothing is happening, your keystrokes are still being correctly recorded.

If this is incorrect, feel free to re-open.

**Comment by Powered87** [comment]
> Hi OP- I don't have a Windows computer anymore, but if memory serves correctly, you just need to type your password and while it looks like nothing is happening, your keystrokes are still being correctly recorded.
> 
> If this is incorrect, feel free to re-open.

Got it, thank you, it does indeed work as you described.
