### ISSUE TITLE
This or This don't work

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#138]
Today the quiz for 50 points don't work.

"This or this"

**Comment by hosein-hub** [comment]
some days "daily set " section perfectly completed and bing dont give us a point and Streak count reseted to 0;
i try it with different ip , browser , phone and systems.
some times after 2 or 3 try its done and received my point , but some times even with 10 try bing dont give me a point.
and i thinks its bing bug , not a project.
i face it with 3 account until today

**Comment by jjjchens235** [comment]
Both my 'this or that' quizzes look to be completed when I checked just now. Closing for now.
