### ISSUE TITLE
[Feature request] Run setup.py in a non interactive shell

### ISSUE THREAD

**Issue by malesci** [jjjchens235/bing-rewards#146]
Is it possible to run setup.py script in a non interactive shell?
I would like to be able to run the setup passing the arguments in a single command line.
like this:
python setup.py --email "email text" --password "secret text" --telegramapi "api text" --telegramuser "user text"

thank you

**Comment by jjjchens235** [comment]
You are right this is a better approach. I will implement this next.

**Comment by jjjchens235** [comment]
malesci - i have added this feature to dev branch, 56caf2a.

You can now create `config.json` by running something like this: `python setup.py -e <email> -p <password>`

Does this implementation work for you?

**Comment by malesci** [comment]
Hello, yes the concept is totally in line. Thank you for this implementation.
I tested the dev branch with the following two scenarios:

```
python setup.py -ta *** -tu ***
python BingRewards/BingRewards.py -r -hl -nc -t -e *** -p ***
```

and
```
python setup.py -e *** -p *** -ta *** -tu ***
python BingRewards/BingRewards.py -r -hl -nc -t
```

In both the case I'm facing this error on telegram msg sending

_Boo! Telegram notification NOT sent, response code is: <Response [404]> with response msg {"ok":false,"error_code":404,"description":"Not Found"}_

maybe I wrong something?

thank you

**Comment by jjjchens235** [comment]
can you compare`BingRewards/config/config.json`  file against `BingRewards/src/config.py` and tell me what the difference is?

**Comment by malesci** [comment]
> can you compare`BingRewards/config/config.json` file against `BingRewards/src/config.py` and tell me what the difference is?

I had some time to test better. In fact it was my mistake because in testing in a hurry I had forgotten the telegram secrets as encoded :)

Now I have tried again with the plain values as arguments on setup.py and I confirm that it works correctly in both scenarios described above.

thank you

**Comment by jjjchens235** [comment]
Good news, thanks for testing it out. I'll move on to your PR update next, will definitely have everything integrated by EOM.

**Comment by jjjchens235** [comment]
56caf2a in master
