### ISSUE TITLE
Add changelog with release versions

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#149]
Not really an issue but I think it would be beneficial wtih all the updates (which are AWESOME) going through to have version count in README as well as BingRewards.py so everyone knows which version (and how many updates behind) they are on.

**Comment by izaac** [comment]
A release version would be cool with changelog.

**Comment by izaac** [comment]
And thanks for this big effort, works really well.

**Comment by jjjchens235** [comment]
Hey thanks for the suggestions guys! 
I have not done this before, I did a little research and it seems that I should create a release within the repo, and then ideally run some auto-changelog generator. Does that sound about right?

Here are the resources I found so far:

1. Release management
    1. github [guide](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)
    2. github_changelog_generator [repo ](https://github.com/github-changelog-generator/github-changelog-generator)

**Comment by jjjchens235** [comment]
[Changelog ](https://github.com/jjjchens235/bing-rewards/blob/dev/CHANGELOG.md)in dev br, will go out in next release.
