### ISSUE TITLE
This or That issue

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#153]
<<< Failed to complete This or That quiz due to following exception:
              >>> Traceback (most recent call last):
  File "/Users/affoghiamoci/Documents/Rewards/BingRewards/src/rewards.py", line 540, in __solve_tot
    current_question, complete_progress = map(
ValueError: invalid literal for int() with base 10: '1 di 10'

**Comment by Affoghiamoci** [comment]
Okay i guess the problem is a language issue, i change “of” in “di” and it seems work, but only in -nhl

**Comment by GreedyJoost** [comment]
I use the following in the rewards.py and It works for me. 
Added:
`progress_split = ' {of} '.format(of=progress.split(' ')[-2])`

Changed:
`                current_question, complete_progress = map(
                    int, progress.split(progres_split)
                )`

It might not be the best solution but I think it is the best quick fix for the way the code is written.

**Comment by jjjchens235** [comment]
@GoostDon sorry just saw this, good idea, in dev now a3eebea
