### ISSUE TITLE
Let's try to solve the localization problem

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#154]
So this thing has been driving me crazy for months now. Although I change the words used to check the completion of the quiz from English to Italian, it still doesn't work. I am sending you the source of my page to see if there is any difference from yours in English.

The page is that of This or That
<img width="808" alt="Schermata 2022-01-17 alle 11 06 37" src="https://user-images.githubusercontent.com/51291350/149749549-9a8733a6-ba96-40ea-b7e4-de75e09a3013.png">

**Comment by jjjchens235** [comment]
#122 duplicate- please move the discussion there.
Regarding your screenshot, the header message `Hai guadagnato...` is in Italian, so yes, there would be a difference.
