### ISSUE TITLE
Empty Tiles get Failed

### ISSUE THREAD

**Issue by Affoghiamoci** [jjjchens235/bing-rewards#157]
>> Trying Giornata di sole
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Giornata di sole
       >> Trying Eucalipto
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Eucalipto

The empthy tiles don’t work anymore, how is their completion checked? I don’t think it’s a language problem this time

**Comment by jjjchens235** [comment]
non-usa
