### ISSUE TITLE
Allow configuration of a discord webhook as an output feed

### ISSUE THREAD

**Issue by tareqx2** [jjjchens235/bing-rewards#158]
Would be a nice feature to allow configuration of a discord webhook, similar to the telegram feed.
In addition, not necessarily in conjunction with, some configuration options for output verbosity. Ideally just having the point stats output is the most useful output to have to discord/telegram

**Comment by ShoGinn** [comment]
I think the solution here is to just add: https://github.com/notifiers/notifiers

If you do that you get any and all notification methods.

**Comment by jjjchens235** [comment]
Shoginn it looks like the repo has providers for everyone BUT discord lol

**Comment by hoseininjast** [comment]
i will work on it in incoming weekend

**Comment by jjjchens235** [comment]
Wanted to call out a change that will most likely affect the implementation of this feature.

I have updated setup.py logic whereby credentials will be added to `config.json` via command-line flags, i.e `python setup.py -e <email> -p`.

If the user needs to enter new credentials in the config, the appropriate arg-parse arguments need to be added to `options.py` NOT setup.py, here is an [example](https://github.com/jjjchens235/bing-rewards/blob/dev/BingRewards/options.py#L74-L83) for telegram.

**Comment by jhaugh0** [comment]
This can very easily be implemented with just a few lines, here's a snippet from an existing project of mine as an example

discordhook = "https://discord.com/api/webhooksxxxxxxxxxxxxxxxxxxxx"
data = {
        "username" : "Uptime Bot",
        "content" : f"storj is not responding\n\n{err}"
        }
requests.post(discordhook, json=data)

**Comment by jjjchens235** [comment]
Jhaugh0's PR:
https://github.com/jjjchens235/bing-rewards/pull/220
