### ISSUE TITLE
Search Query Updating 

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#162]
I have noticed that the program fails to complete searches sometimes due to not having sufficient new queries to search. 
Upon further analysis, this is because the trending_date used is always the current datetime. This means that if the program tries to find more queries, it'll get most of the same queries it's already used as it's just checking the trending searches maybe 20-60 seconds after it last checked.

I propose that the trending_date progressively gets subtracted as more 'new' queries are demanded.
This would be done in BingRewards/src/rewards.py in __search

I'm not sure what to suggest as the subtraction amount, as I've never used google trends before and don't know how drastically the queries vary over time. Any clues?

**Comment by ShoGinn** [comment]
@JartanFTW you can try my repo until and if this gets merged!

**Comment by JartanFTW** [comment]
@ShoGinn I made some notes in your pull request whenever you have a chance to check them out. Thanks for making these changes so quickly!

**Comment by ShoGinn** [comment]
Easy enough! I try and see if I can help where I can.
