### ISSUE TITLE
Possible Xbox task automation

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#164]
This reddit thread explains how one can complete the Xbox tasks from a computer.

https://www.reddit.com/r/MicrosoftRewards/comments/rybmsv/you_can_now_complete_all_xbox_tasks_on_your_pc/

This is done with an app, and the limitations of it make it infeasible to use, however it may be possible for someone to track the requests made by the app and replicate them via code. I unfortunately don't have those expertise.

If anyone is interested in fiddling around with this, I'd be very interested to see what comes of it!

**Comment by ShoGinn** [comment]
I attempted to reverse engineer the headers of the app when this came out to then emulate using requests or selenium. But because the app uses a weird authentication that was outside my scope I decided that greed for points was not worth the risk or flagging an account by brute force.

My kids use the xbox to do the "extras" and the penance that is the daily searches and quizzes is done automated.

**Comment by JartanFTW** [comment]
> I attempted to reverse engineer the headers of the app when this came out to then emulate using requests or selenium. But because the app uses a weird authentication that was outside my scope I decided that greed for points was not worth the risk or flagging an account by brute force.
> 
> My kids use the xbox to do the "extras" and the penance that is the daily searches and quizzes is done automated.

Interesting that you had the same idea!
Perhaps someone else will have better luck.

**Comment by jjjchens235** [comment]
The reddit solution requires use of the MS app on desktop, not a solution for browser/selenium.

**Comment by JartanFTW** [comment]
> This is done with an app, and the limitations of it make it infeasible to use, however it may be possible for someone to track the requests made by the app and replicate them via code. I unfortunately don't have those expertise.
