### ISSUE TITLE
Punch Card Logic

### ISSUE THREAD

**Issue by Powered87** [jjjchens235/bing-rewards#169]
Checking the account today, there was no entry in the error log and the run log says successful.

But the Punch Card was not completed, it only completed the quiz portion and not the easy click to open links. I know this repo mentions that only US Punch Cards are guaranteed, while I am in Canada.
![image](https://user-images.githubusercontent.com/20592762/153306078-4a174b45-31d9-46f8-a14f-050adaffb0be.png)

However, I also saw in the acknowledgment section that you credit the punch card code to Charlesbel's repo for MSfarmer. When I tested his MSFarmer script, it successfully completed the entire punch card.

I guess my question is if the punch card logic is significantly different between the two and if should I just run both scripts daily? Or if there are plans to update the Punch Card code?

**Comment by jjjchens235** [comment]
In the US version, MS only lets you do one activity each day.
```
Do you know the names of the most well known K-pop band's members? 
To get your second punch, wait 24 hours or more after completing Day 1.
```

So in the code, it only attempts 1 punch-card activity each day.


If the current code is able to complete the punch-card over 4 days, I'm probably not going to update the code. However, if it fails on completing an activity, then I'll have to update it.

**Comment by Powered87** [comment]
Got it, that makes sense and good to know. I will provide an update in a few days!
Thanks!

**Comment by Powered87** [comment]
> In the US version, MS only lets you do one activity each day.
> 
> ```
> Do you know the names of the most well known K-pop band's members? 
> To get your second punch, wait 24 hours or more after completing Day 1.
> ```
> 
> So in the code, it only attempts 1 punch-card activity each day.
> 
> If the current code is able to complete the punch-card over 4 days, I'm probably not going to update the code. However, if it fails on completing an activity, then I'll have to update it.

Yep, works exactly as you described. Thank you.
