### ISSUE TITLE
REFACTOR: after_click_on is not an AbstractEventListener element.

### ISSUE THREAD

**Issue by ShoGinn** [jjjchens235/bing-rewards#174]
https://github.com/jjjchens235/bing-rewards/blob/94feb553a1132d0569a2ae3ff575f458664d7a56/BingRewards/src/driver.py#L18-L25

I was doing coverage tests and noticed that this never gets executed and I was curious why.

https://www.selenium.dev/selenium/docs/api/py/webdriver_support/selenium.webdriver.support.abstract_event_listener.html#selenium.webdriver.support.abstract_event_listener.AbstractEventListener.after_click

Solution:
```python


    def after_click(self, url, driver):
        animation = r"try { jQuery.fx.off = true; } catch(e) {}"
        driver.execute_script(animation)

```

**Comment by ShoGinn** [comment]
Pull request submitted #177

**Comment by jjjchens235** [comment]
Thanks ShoGinn, this has been merged
