### ISSUE TITLE
Fails sign-in if account has last signed in with email confirmation

### ISSUE THREAD

**Issue by b-** [jjjchens235/bing-rewards#189]
If you sign into your Microsoft Account by way of getting a code from your email, your account defaults to that mode of authentication until the next time you sign in with your password.

Of course this script cannot get a code from your email (perhaps it could be extended to wait for user to enter one?) but what it _should_ do is:

1. check if we're being asked for email proof
2. click "Other ways to sign in" (ID: idA_PWD_SwitchToCredPicker)
3. Click "Use my password" (aria-label="Use my password")
4. continue signing in

**Comment by jjjchens235** [comment]
Thanks for reporting. Please submit a PR if you're so inclined.

**Comment by b-** [comment]
Okay, understandable. I'm not really sure where to begin myself, though -- I was trying to dive into the code, but I really don't understand what's going on in the authentication flow…

**Comment by jjjchens235** [comment]
Assuming the `email proof page` is a separate URL...

I would probably add the code [here](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L140).

And here what the pseudo code might look like:

```py
elif 'email proof' in URL:
    # click other ways to sign in
    self.driver.find_element(By.ID, idA_PWD_SwitchToCredPicker').click()
    time.sleep(2)
    ## click use my PW
    self.driver.find_element(By.ID, '<use_my_pw_element>').click()
```

**Comment by jjjchens235** [comment]
stale cornercase
