### ISSUE TITLE
Glad You Were Able to Reupload

### ISSUE THREAD

**Issue by z0oinks** [jjjchens235/bing-rewards#19]
If this is the same script that I've been using for the past couple years, thanks for reuploading it! I have a copy saved, but it was weird to see it gone a few weeks ago and not find any mention of it anywhere.

Is this still being maintained and developed, or is this new repo just for "archival" purposes?

**Comment by jjjchens235** [comment]
No problem, it's been fun. 
Hmm, the original owner originally removed it 1.5 years ago, and this version has been up ever since. Not sure what you mean by gone for a few weeks, maybe you're referring to a different repo that was also forked from the original?

It is still being maintained.

**Comment by z0oinks** [comment]
Ah yeah. I was thing xMNG, which I saw in the other thread that this isn't that

Either way, good to have something active!
