### ISSUE TITLE
Schedule Windows

### ISSUE THREAD

**Issue by LCzoboriek** [jjjchens235/bing-rewards#198]
Hi, apologies but i see no way to ask questions about this other then opening up an issue, if theres a server to ask questions please direct me!

Otherwise im having an issue with my windows scheduler, and im not sure what im doing wrong. Ive followed the instructions to the letter, the only part om not so sure on is the absolute path bit, my repository is located C:\Users\ldccz\Documents\GitHub\bing-rewards, so would i put that in the start in section of the scheduler? If so then when i click run, it doesnt seem to do anything, i am always having to run in nhl mode for some reason unknown to me, would that be affecting it? Any help would be greatly appreciated

**Comment by jjjchens235** [comment]
you mind sharing a screenshot?

**Comment by LCzoboriek** [comment]
Yeh sure! What would you like the screenshot of? My task schedule settings?

**Comment by jjjchens235** [comment]
yea the settings specific to the Bingrewards task you created

**Comment by LCzoboriek** [comment]
![image](https://user-images.githubusercontent.com/56021888/161530571-23073856-ce1b-41ce-aba1-7b887a70a9df.png)
C:\Users\ldccz\Documents\GitHub\bing-rewards is where i start in
BingRewards/BingRewards.py -nhl is the command
C:\Users\ldccz\AppData\Local\Programs\Python\Python310\python.exe and thats the program/script i choose in action

**Comment by jjjchens235** [comment]
I suspect that
`C:\Users\ldccz\Documents\GitHub\bing-rewards`
should be
`C:\Users\ldccz\Documents\GitHub\bing-rewards-master`

**Comment by LCzoboriek** [comment]
Okay lemme try changing that

**Comment by LCzoboriek** [comment]
Unfortunately that didnt work, it wont run at all, before it was running but wasnt actually doing anything, the last run result was (0x1) if that indicates to anything?

**Comment by LCzoboriek** [comment]
Retrack that, 
![image](https://user-images.githubusercontent.com/56021888/161724726-178ac886-60f3-4c54-96dc-763cd549409a.png)
This is what i see now, it says running but no pop up of a browser has occured

**Comment by LCzoboriek** [comment]
Im an idiot, i didnt set the users group as administrator, its working now :)
Ill close the issue
