### ISSUE TITLE
Rewards Page has changed

### ISSUE THREAD

**Issue by ZestyNachos** [jjjchens235/bing-rewards#199]
First of all  just wanted to say thanks for your great work on this.

I ran it this morning and was getting a timeout error so I ran it again in headless mode.

It appears the rewards page link has changed from https://account.microsoft.com/rewards/ to https://rewards.microsoft.com/

**Comment by heximing** [comment]
same issue here.

**Comment by iTaKK** [comment]
I changed the link to https://rewards.microsoft.com/ in lines 23 and 195 in rewards.py and it ran without error.

**Comment by heximing** [comment]
Thanks very much.
 line 23 change from "https://account.microsoft.com/rewards/" to "https://rewards.microsoft.com/"
line 195 change from "https://rewards.microsoft.com/welcome" to "https://rewards.microsoft.com/"
works for me now. Thanks.

**Comment by ZestyNachos** [comment]
Thanks, that's worked for me as well. I figured there would be something like that in the code but didn't have a chance to look.

**Comment by dfault-user** [comment]
ill just push a commit using github's editor of wonders

**Comment by WangZhuo2015** [comment]
Thanks, it worked for me after modifying these two lines of code.

**Comment by dfault-user** [comment]
eh, after reviewing contrib guidelines, one moment

**Comment by LCzoboriek** [comment]
Changed lines myself and that fixed that problem, thanks

**Comment by wastingoctober** [comment]
> I changed the link to https://rewards.microsoft.com/ in lines 23 and 195 in rewards.py and it ran without error.
This worked for me as well. Thanks for the update.

**Comment by dfault-user** [comment]
Merged in #200
