### ISSUE TITLE
Feature Request - Allow "geo" on search queries to be passed from config or switches

### ISSUE THREAD

**Issue by AnthonyBe** [jjjchens235/bing-rewards#202]
I know I can just change line 274 in rewards.py from `geo = "US"` to, say, `geo = "GB"` but I was wondering if you would be open to making this a config variable or cmd line switch?

This would mean the searches would match a locale of the user and be less suspicious.

**Comment by jjjchens235** [comment]
that's a good idea- I would probably prefer this to be a cmd line var over config.

feel free to submit a pr, or I can add it at some pt.

**Comment by AnthonyBe** [comment]
Cheers. My coding skills are woeful so I'll just hard-code mine for now and put this on your backburner :)

I was assuming that you could use anything listed as a valid market locale in line 174:
`VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR', 'mkt=ES-ES', 'mkt=EN-AU', 'mkt=ZH-CN', 'mkt=IT-IT', 'mkt=DE-DE']`
so not sure if you want to restrict is to just the EN lang locales (i.e. US, GB, AU and I know you can also do CA) but potentially the non-EN locales by passing the `lang `and `geo `vars from the market?

**Comment by jjjchens235** [comment]
The `valid_markets` codes is taken from the markets that Microsoft Rewards serves.

However, the `geo` and `lang` variables are for the `Google Trends` API. Maybe they use the same country code and language codes, I'm not sure.

1. Here is a full list of the google language codes: https://sites.google.com/site/tomihasa/google-language-codes
3. And here are the common country codes: https://www.iban.com/country-codes

**Comment by jjjchens235** [comment]
Ok, I did some quick work on this in my local branch.

```sh
python BingRewards.py -e ema123@gmail.com -p -w  -nhl --google-trends-geo MX
```

The above would allow you to search for trending topics in MX (Mexico). Would this work for you?

**Comment by jjjchens235** [comment]
In dev branch now, 8a43ab8

Let me know if you run into any issues.
