### ISSUE TITLE
[Request] Send Telegram Message on 2FA request

### ISSUE THREAD

**Issue by chen-ye** [jjjchens235/bing-rewards#214]
I would love if the bot would be able to send the "Waiting for user to approve 2FA, please select 54 in Microsoft Authenticator" message to Telegram--allowing users to approve 2FA requests from non-interactive sessions.

Can probably throw together a PR over the weekend--I figure you could pass a `send_message` callback into the `Rewards` constructor or the `complete_search` method.

**Comment by jjjchens235** [comment]
good idea, looking forward to seeing what you come up with

**Comment by wastingoctober** [comment]
I like this idea too. I can't tell you how many times I'm doing something else and miss the notification for the mobile search. Or if I'm remotely connected to my computer, it's just too hard to go back and forth between authenticator and RDP in time. Lmk if you need another tester.

**Comment by chen-ye** [comment]
Forgot about this--opened a PR on #236

**Comment by jjjchens235** [comment]
https://github.com/jjjchens235/bing-rewards/pull/236
