### ISSUE TITLE
[Question] How can I use this as a container and how can I use this while having passwordless enabled on my Microsoft account?

### ISSUE THREAD

**Issue by Aholicknight** [jjjchens235/bing-rewards#217]
I have a couple of questions regarding bingrewards 

1. Is it possible to use this repo as a [replit](https://replit.com/) to run without my computer being on? I know some GitHub repos using replit such as [nitro-sniper](https://github.com/localip/nitro-sniper/wiki/Installation) then it uses [uptime-robot](https://uptimerobot.com/) to ping the replit host to make sure it stays online, you can set it to ping every hour, every x day, etc, or is it possible to set this up as an Azure / Google Cloud container? 

2. I was thinking about enabling the [passwordless feature](https://www.microsoft.com/security/blog/2021/09/15/the-passwordless-future-is-here-for-your-microsoft-account/) for my Microsoft account to make signing in easier, is it possible to use bingrewards if I have this enabled or does 2FA have to be disabled? 

Thank you for answering my questions!

**Comment by jjjchens235** [comment]
1. It's possible, but the container logic, i.e Docker would need to be implemented.
2. Yes, more info here: https://github.com/jjjchens235/bing-rewards#additional-login-security-options

**Comment by jjjchens235** [comment]
This would solve it, closing
https://github.com/jjjchens235/bing-rewards/issues/206

**Comment by Killerherts** [comment]
Wouldn't this require setup.py to be part of BingRewards.py ?
