### ISSUE TITLE
Stuck on a Task

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#225]
The script gets stuck when doing 
    >> Trying Task #5 | Xbox One or Xbox Series X|S
        >>> Checking cookies popup
Ran it in -nhl and it is stuck on a blank Untitled page. Had to ^c the script to get an error log cause it wasn't timing out (again just stuck on the page without moving on
[error.log](https://github.com/jjjchens235/bing-rewards/files/8812800/error.log)
)

**Comment by jjjchens235** [comment]
I ran into the same problem. However, as I was testing out a solution it looks like Microsoft removed this Offer, as I suddenly no longer see it.

**Comment by coollbv** [comment]
Indeed, it seems the page it was suppose to open was faulty. However, maybe this can be used to create a failsafe in case that happens again and skips to the next task so it doesn't freeze up entire process...

**Comment by coollbv** [comment]
Looks like it is getting stuck on
    >> Punch card "Stranger Things Season 4" is not complete yet.
    >> Starting activity "Get the app"
as well

**Comment by jjjchens235** [comment]
Agreed a failsafe would be ideal, but difficult to test if I cannot reproduce the error. Will keep in mind for sure.

regarding stranger things, are you using most updated code? I believe this was fixed in https://github.com/jjjchens235/bing-rewards/issues/221

**Comment by coollbv** [comment]
You sir are correct, I wasn't up to date...
