### ISSUE TITLE
Mac Monterey Terminal syntax from pip, python to pip3, python3

### ISSUE THREAD

**Issue by mgrimace** [jjjchens235/bing-rewards#226]
Hello a small contribution here from a Mac 12.4 Monterey Terminal user:

from `pip` to `pip3`
from `python` to `python3`

**Comment by mgrimace** [comment]
also needed a manual install of chromedriver `brew install chromedriver`

**Comment by mgrimace** [comment]
Fixing error: “chromedriver” cannot be opened because the developer cannot be verified. Unable to launch the chrome browser on Mac OS

`xattr -d com.apple.quarantine /usr/local/bin/chromedriver` should remove it from Mac quarantine

**Comment by jjjchens235** [comment]
python or python3 is going to vary from user to user based on how they installed python, i will let that be an exercise for the reader.
you are installing chromedriver in an alternative way via homebrew which is fine, but not strictly necessary.
