### ISSUE TITLE
Selenium does not work correctly on Ubuntu server

### ISSUE THREAD

**Issue by Fireblossom** [jjjchens235/bing-rewards#231]
Hi, I'm trying to use corn to perform daily tasks on my Ubuntu 20.04.4 LTS server.
It stuck [here](https://github.com/jjjchens235/bing-rewards/blob/bedf8358f841f897d791db5d38043857971c9417/BingRewards/src/driver.py#L195) and always waiting for the driver.

In debug mode, I find it always returns error `DevToolsActivePort file doesn't exist`

To solve this problem, I followed the solution in [this thread](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2473) and added `options.add_argument("--remote-debugging-port=9222")` to the options, and it works... partially

Now it stuck [here](https://github.com/jjjchens235/bing-rewards/blob/bedf8358f841f897d791db5d38043857971c9417/BingRewards/src/rewards.py#L155).
It looks like `self.driver.get("https://login.live.com/")` does not return for a long time.
But, in the debug console, I tried `self.driver.get("https://google.com/")` and it executed normally.

I have also tried initializing with the same options in a new script 
```python
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
driver.get("https://login.live.com/")
```
and it works fine.

Now I'm completely out of ideas, can you help? Thanks!

**Comment by Fireblossom** [comment]
Update: 
After a few days of investigation, I find that this is just because, Selenium can not run on the Oracle cloud x86 machine, for some unknown reason...
I moved the repo to an ARM machine and it works well.

I‘m closing this issue because it is not an error related to this project.
And thank you for providing this great project!

**Comment by islamheroooo** [comment]
Hi @Fireblossom
I need your help to make selenium run on ARM If you don't mind.
This is my telegram user-id ==> GithubMac 
If you could contact me in your free time I will really appreciate that.
Thanks

**Comment by sigma67** [comment]
Curious how you managed the requirement to sign in manually before first use on a server? Stuck here currently.
