### ISSUE TITLE
How to customize for another Country?

### ISSUE THREAD

**Issue by DerMuffin** [jjjchens235/bing-rewards#234]
What i need to do to customize this script for another country?

**Comment by jjjchens235** [comment]
Does the country use English on the reward page?

If so, it might be as simple as adding the valid market to the following list in rewards.py:
```py
        VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR', 'mkt=ES-ES', 'mkt=EN-AU', 'mkt=ZH-CN', 'mkt=IT-IT', 'mkt=DE-DE']
```

If it's a non-English country, then you would have to re-write any differing logic.
