### ISSUE TITLE
Ability to Trust a Device with no Display

### ISSUE THREAD

**Issue by holty07** [jjjchens235/bing-rewards#237]
I am trying to get this running in a remote server on Oracle Cloud free tier. I have everything almost ready to go but it is getting stuck at the "You Selected Remaing" step and doesn't continue. I have a feeling it may be prompting for something like trust this device. Is there a way to trust the server?

**Comment by jjjchens235** [comment]
I think you have to run the program using the `--no-sandbox` flag assuming it's a Linux machine.
There is also a docker image of this code you can use within your VM
