### ISSUE TITLE
Sign in with password instead of email code

### ISSUE THREAD

**Issue by Luffitys** [jjjchens235/bing-rewards#242]
Since bing-rewards has login issues for some users due to this error:
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="idRemoteNGC_DisplaySign"]"}

Which happens, because Microsoft sends a code to the email, but bing-rewards doesn't support it yet, My suggestion would be to add an option to do the following login process instead:

![image](https://user-images.githubusercontent.com/51169632/177003496-e07f4eb0-d207-4ab0-9f9b-c9852df54457.png)

![image](https://user-images.githubusercontent.com/51169632/177003507-34798949-74b8-40a2-a0d4-8c60d40a980b.png)

![image](https://user-images.githubusercontent.com/51169632/177003545-c2394581-3b06-4b59-911b-e50fdba080dd.png)

**Comment by Luffitys** [comment]
#213

**Comment by b-** [comment]
Duplicate of https://github.com/jjjchens235/bing-rewards/issues/189
