### ISSUE TITLE
Scheduling automatic updating in Windows?

### ISSUE THREAD

**Issue by riahc3** [jjjchens235/bing-rewards#247]
Hello

You mention there is a script for updating the repo.

Does it work in Windows and how can I schedule for autoupdate?

Thank you

**Comment by jjjchens235** [comment]
It's a bash script, so you can run it in Windows manually, but you need to be using the appropriate shell (i.e git bash, wsl, etc).

Regarding the auto-update, if you want to use task scheduler, you would do something like this, per [stackoverflow](https://superuser.com/questions/1461310/how-to-run-a-bash-script-with-task-scheduler-windows-10-v1903):
1. create a `batch` windows job
2. have the batch job call the `bash script`
3. schedule the batch job in task scheduler

**Comment by jjjchens235** [comment]
stale
