### ISSUE TITLE
Consistently failing all searches

### ISSUE THREAD

**Issue by Shark3900** [jjjchens235/bing-rewards#252]
**Before posting issue...**

1. Run using non-headless mode: `python BingRewards -nhl`
2. Copy relevant output from `errors.log`

**Your Issue - include the details from the above steps:**

I only found this project a few days ago - and for the first couple days it worked great. About 3 days ago, it stopped working - consistently failing web searches & mobile searches.

I don't get any errors, just "failed search". Interestingly enough, running in no-headless mode, it looks like everything works and that it's just not incrementing the searches. I gain a few points each attempt, around 9-15, but it reads as failed and stops trying.

I've tried all that I can think of: Upgrading chrome (couldn't downgrade), fresh installing both chrome and the bot, trying dev and 1.11 (using 1.12 the most), tried using edge, unsure as to what I'm missing. I feel like it's obvious but couldn't find anything similar when looking through the issues myself, sorry if it's trivial.

Relevant logs below:

> Fri, Jul 22 2022 05:29PM
       >> Logging in
       >> Waiting for user to approve 2FA, please select 62 in Microsoft Authenticator
           << Successfully logged in
> Starting Edge search
       >> Starting search
             >>> Progress: [                              ] 0/20 (0%)
           << Failed to complete search
    < Failed to complete Edge search

> Starting Mobile search
       >> Starting search
             >>> Progress: [                              ] 0/100 (0%)
           << Failed to complete search
    < Failed to complete Mobile search

> Starting Web search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [                              ] 0/150 (0%)
           << Failed to complete search
    < Failed to complete Web search

> Starting Offers
       >> Trying Flutter by
           << Already completed, or no points offered
       >> Trying Test your smarts
              >>> Checking cookies popup
              >>> No cookie popup present
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                    >>>> Progress: [##############################] 10/10 (100%)
                  <<< Successfully completed quiz2
           << Successfully completed 'Test your smarts'
       >> Trying Daily poll
              >>> Starting poll
                  <<< Successfully completed poll
           << Successfully completed 'Daily poll'
       >> Trying You've earned a badge!
           << Already completed, or no points offered
       >> Trying Give with Bing
           << Already completed, or no points offered
       >> Trying Collections in Microsoft Edge
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete 'Collections in Microsoft Edge'
       >> Trying MLB matchups
           << Already completed, or no points offered
       >> Trying Aaaannnndd... action!
           << Already completed, or no points offered
       >> Trying Customize with extensions
           << Already completed, or no points offered
       >> Trying Rewards in your browser
           << Already completed, or no points offered
       >> Trying Get moving to stay fit
           << Already completed, or no points offered
       >> Trying Search, shop & more on the go
           << Already completed, or no points offered
       >> Trying This or That?
           << Already completed, or no points offered
       >> Trying Supersonic quiz
              >>> Starting quiz
              >>> Multiple Answers
                    >>>> Progress: [##############################] 3/3 (100%)
                  <<< Quiz complete
           << Successfully completed 'Supersonic quiz'
       >> Trying Know your celebrity news?
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                    >>>> Progress: [##############################] 7/7 (100%)
                  <<< Successfully completed quiz2
           << Successfully completed 'Know your celebrity news?'
       >> Trying This or That?
              >>> Starting quiz
                    >>>> Progress: [##############################] 10/10 (100%)
           << Successfully completed 'This or That?'
    < Failed to complete Offers

> Summary
       >> Points earned this run: 36
       >> Microsoft 'Points earned' today: 228
       >> Streak count: 2
       >> 0 day
       >> Available points: 2,629
       >> Lifetime points: 2,639

>"Thu, Jul 21 2022 01:52PM: Points earned this run: 49; Microsoft 'Points earned' today: 192; Streak count: 2; 0 day; Available points: 2,384; Lifetime points: 2,394",
> "Thu, Jul 21 2022 02:04PM: Points earned this run: 36; Microsoft 'Points earned' today: 192; Streak count: 2; 0 day; Available points: 2,420; Lifetime points: 2,430",
>"Thu, Jul 21 2022 02:27PM: Points earned this run: 15; Microsoft 'Points earned' today: 192; Streak count: 2; 0 day; Available points: 2,447; Lifetime points: 2,457",
>"Thu, Jul 21 2022 02:34PM: Points earned this run: 12; Microsoft 'Points earned' today: 192; Streak count: 2; 0 day; Available points: 2,459; Lifetime points: 2,469",
>"Thu, Jul 21 2022 02:43PM: Points earned this run: 9; Microsoft 'Points earned' today: 192; Streak count: 2; 0 day; Available points: 2,468; Lifetime points: 2,478",
>"Fri, Jul 22 2022 05:16PM: Points earned this run: 125; Microsoft 'Points earned' today: 228; Streak count: 2; 0 day; Available points: 2,593; Lifetime points: 2,603",
>"Fri, Jul 22 2022 05:29PM: Points earned this run: 36; Microsoft 'Points earned' today: 228; Streak count: 2; 0 day; Available points: 2,629; Lifetime points: 2,639"

**Comment by Killerherts** [comment]
Try running without headless you might be able to see where things are failing.

**Comment by Shark3900** [comment]
Mentioned that in the post!

>I don't get any errors, just "failed search". Interestingly enough, running in no-headless mode, it looks like everything works and that it's just not incrementing the searches. I gain a few points each attempt, around 9-15, but it reads as failed and stops trying.

Appreciate the effort though, I don't blame you for missing it since the output takes up ~80% of the ticket.

**Comment by Killerherts** [comment]
opps my bad you could try pulling down my docker container

**Comment by Shark3900** [comment]
I probably messed something up - but when I tried your docker it just hung on "You selected remaining".

Appreciate the help though!

**Comment by Killerherts** [comment]
> I probably messed something up - but when I tried your docker it just hung on "You selected remaining".
> 
> Appreciate the help though!

Typically I see that when I forget to add the nsb flag make sure you run it like python BingRewards.py -nsb

**Comment by 03-JOHN-21** [comment]
> I probably messed something up - but when I tried your docker it just hung on "You selected remaining".
> 
> Appreciate the help though!

hey shark. i’ve been trying to get this to work for a while. no luck. i’m having somewhat of a similar issue. is there a way i can contact you to get some help? discord would be preferred. thanks

**Comment by Shark3900** [comment]
> > I probably messed something up - but when I tried your docker it just hung on "You selected remaining".
> > Appreciate the help though!
> 
> Typically I see that when I forget to add the nsb flag make sure you run it like python BingRewards.py -nsb

Oh hey, that worked! Awesome, thank you! It's working as I type this - Edge Search 20/20 and Mobile 60/100.
Makes the underlying problem all the more strange (at least for me), but glad that works if nothing else.



> hey shark. i’ve been trying to get this to work for a while. no luck. i’m having somewhat of a similar issue. is there a way i can contact you to get some help? discord would be preferred. thanks

Sure, granted anything I could help you with is probably in this thread lol.
Shark3900#9016

**Comment by Killerherts** [comment]
Np mark the issue closed if you don't mind cheers

**Comment by Shark3900** [comment]
Sure thing, wanted to make sure it was just the -nsb argument that was the sole reason. 
Turns out it was!
Cheers and thanks for all the help Killerherts.
