### ISSUE TITLE
Choose chrome or edge profile

### ISSUE THREAD

**Issue by jerbear2008** [jjjchens235/bing-rewards#254]
Is there a way to select which chrome or edge profile to launch with? I have many profiles, and I am not logged in on all of them. It would be very convenient if I could specify the user data directory to the script to select my profile.

Is this currently possible, or do I misunderstand the script and it is not necessary?

**Comment by jjjchens235** [comment]
Do you mean profile as in account? You can specify the email / pw like so:

```sh
 python BingRewards.py -e <email> -p -d <msedge|chrome>
```

**Comment by b-** [comment]
I'm pretty sure @jerbear2008 is referring to the profile selector in the browser itself -- in the toolbar.

This is something I found quickly on stackoverflow: https://stackoverflow.com/questions/52394408/how-to-use-chrome-profile-in-selenium-webdriver-python-3/67389309#67389309
