### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by royaltongue** [jjjchens235/bing-rewards#26]
```
localuser@bryanLinux:~$ sh ~/bingrewards/msaccount.sh 
['Thu, Mar 19 2020 09:40PM', 'Failed Mobile Search, Offers']

	You selected remaining

> Starting offers
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "BingRewards.py", line 99, in __main
    rewards.complete_offers()
  File "/home/localuser/Documents/bingrewardsjj/msaccount/BingRewards/src/rewards.py", line 811, in complete_offers
    driver = self.__complete_offers()
  File "/home/localuser/Documents/bingrewardsjj/msaccount/BingRewards/src/rewards.py", line 738, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "/home/localuser/Documents/bingrewardsjj/msaccount/BingRewards/src/rewards.py", line 655, in __offers
    return min(completed)
ValueError: min() arg is an empty sequence
```

where msaccount.sh is just 

```
cd ~/Documents/bingrewardsjj/msaccount/BingRewards
python3 BingRewards.py -r
```

**Comment by jjjchens235** [comment]
Within rewards.py, in the method     def __offers(self, driver):
can you adjust the code to this and see if it works? I think there are some issues with the offers that need to be fixed, but this will let you at least proceed to mobile searches:

```
   except NoSuchElementException:
            return -1
```

**Comment by royaltongue** [comment]
Changed it now, I'll post an update in a day or so!

**Comment by royaltongue** [comment]
Sorry... time got away from me!

Just checked and it's still failing mobile searches

```Thu, Mar 19 2020 01:48PM: Failed Mobile Search, Offers
Thu, Mar 19 2020 07:09PM: Failed Mobile Search, Offers
Thu, Mar 19 2020 09:40PM: Failed Mobile Search, Offers
Thu, Mar 19 2020 09:40PM: Failed Mobile Search, Offers
Thu, Mar 19 2020 09:41PM: Failed Mobile Search, Offers
Fri, Mar 20 2020 09:37AM: Failed Mobile Search, Offers
Fri, Mar 20 2020 10:58AM: Failed Offers
Fri, Mar 20 2020 01:48PM: Failed Offers
Fri, Mar 20 2020 07:09PM: Failed Offers
Sat, Mar 21 2020 09:37AM: Failed Offers
Sat, Mar 21 2020 01:48PM: Failed Offers
Sat, Mar 21 2020 07:09PM: Failed Offers
Sun, Mar 22 2020 09:37AM: Failed Mobile Search, Offers
Sun, Mar 22 2020 01:48PM: Failed Mobile Search, Offers
Sun, Mar 22 2020 07:09PM: Failed Mobile Search, Offers
Mon, Mar 23 2020 09:37AM: Failed Mobile Search, Offers
Mon, Mar 23 2020 01:48PM: Failed Mobile Search, Offers
Mon, Mar 23 2020 07:09PM: Failed Mobile Search, Offers
Tue, Mar 24 2020 09:37AM: Failed Mobile Search, Offers
Tue, Mar 24 2020 01:48PM: Failed Mobile Search, Offers
Tue, Mar 24 2020 07:09PM: Failed Mobile Search, Offers
Wed, Mar 25 2020 09:37AM: Failed Mobile Search, Offers
Wed, Mar 25 2020 01:48PM: Failed Mobile Search, Offers
Wed, Mar 25 2020 07:09PM: Failed Mobile Search, Offers
Thu, Mar 26 2020 09:37AM: Failed Mobile Search, Offers
Thu, Mar 26 2020 01:48PM: Failed Mobile Search, Offers
Thu, Mar 26 2020 07:09PM: Failed Mobile Search, Offers
Fri, Mar 27 2020 09:37AM: Failed Mobile Search, Offers
Fri, Mar 27 2020 01:48PM: Failed Mobile Search, Offers```

**Comment by royaltongue** [comment]
Strangely though, error.log doesn't report any real errors after I changed rewards.py.
The last error was the same as in the OP

**Comment by sickosimmons** [comment]
having same issue with failed mobile search

**Comment by snoweey** [comment]
Mobile search had been also failing for me started after the Linux driver was added. I will try to post logs after I get home later

**Comment by jjjchens235** [comment]
> Strangely though, error.log doesn't report any real errors after I changed rewards.py.
> The last error was the one in the OP

tl, dr: two issues, one was value error causing program to crash, second issue was mobile user agent needed to be updated

Thanks for checking again. I think there were two issues at play. The value error issue was occurring because the offer web element could not be located and the error handling wasn't handling this correctly, so the program aborted and the error msg was displayed.

Once you adjusted the return statement, the program quit the offers section, and proceeded to the mobile searches. 

Strangely, this error never occurred for me, and I suspect for most people, or else there would be people chiming in.

Once you were able to proceed to the mobile searches the second issue occurred . Based on some reddit threads, I believe Bing adjusted what would be recognized as a mobile search- the search had to be run inside an Edge browser. Since the old mobile agent wasn't using edge, the program would search 3 different times, and once the score didn't change, the program would quit, without an error msg.

**Comment by jjjchens235** [comment]
> Mobile search had been also failing for me started after the Linux driver was added. I will try to post logs after I get home later

I was having the same issues with mobile for the past week. I have updated the code with a new mobile user agent (that now includes Edge browser), and the mobile searches now work for me.

**Comment by gaiacanon** [comment]
I'll give it a shot and report back!

**Comment by royaltongue** [comment]
I'll give it a shot and report back!

Thanks!

**Comment by snoweey** [comment]
It seems to be working for me
