### ISSUE TITLE
[Feature Request] - Run offers with user-agent for Edge

### ISSUE THREAD

**Issue by SimpsomRJ** [jjjchens235/bing-rewards#267]
Some of the recent offers are requiring that you browse with Edge to register properly. Can you change the code to go through the offers with the user-agent for Edge by default?

I use this code on a headless machine with docker and have been seeing failures on offers because of requests like this. This would make the go through and get us all the points.

**Comment by jjjchens235** [comment]
The user agents are already using edge by default. That's how the `edge searches` are being completed...

The code
```py
    __WEB_USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33"
    __MOBILE_USER_AGENT = "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.5195.79 Mobile Safari/537.36 EdgA/100.0.1185.50"
```

**Comment by jjjchens235** [comment]
stale
