### ISSUE TITLE
[Feature Request] - Allow use of fresh account

### ISSUE THREAD

**Issue by aydynx** [jjjchens235/bing-rewards#268]
when using a completely fresh Microsoft account, i get the initial microsoft rewards setup pages, is it possible to have the bot complete these for me?

**Comment by DimaRazb** [comment]
It will complete it for you to Level 1. You have to probably run it the next day to get to Level 2.

**Comment by aydynx** [comment]
no it doesnt. to clarify, i am talking about accounts that see the sign up screen when visiting rewards.microsoft.com

**Comment by DimaRazb** [comment]
Well, to clarify the info you could get from the readme:
1) you have to log in once to the website (personally I install a desktop for my ubuntu for this only).
2) You have to run the script several times after logging in once to get all points collected and to achieve Level 2.

**Comment by jjjchens235** [comment]
Which set-up pages are you referring to?

It currently completes the following:
- approve sign in page
- stay signed-in page
- agree to terms/conditions
- security info still accurate
- confirm identity

If these pages are not currently being automated, plz lmk.

If there are more pages that you feel are automable please share the following:
- URL
- some  element identifier of the 'proceed' button

**Comment by jjjchens235** [comment]
stale
