### ISSUE TITLE
Upgrade script for Windows?

### ISSUE THREAD

**Issue by riahc3** [jjjchens235/bing-rewards#270]
I see that the upgrade script is for bash. Anything for Windows?

**Comment by fexofenadine** [comment]
git pull

**Comment by Killerherts** [comment]
The script works for both you just have to clone the repo with git first

**Comment by jjjchens235** [comment]
What shell are you using, the default `command prompt`?
In the past, I've had success with both `Git Bash` shell and `WSL`, more info in this [StackOverFlow](https://stackoverflow.com/a/6413405)
