### ISSUE TITLE
More like a question but where do I run the lil text from step 3?

### ISSUE THREAD

**Issue by jawdropper16** [jjjchens235/bing-rewards#275]
like I try to run in python but nothing happens 
![image](https://user-images.githubusercontent.com/104870012/189546040-68ceeea0-55cd-46f1-99ed-a75a09285d24.png)

**Comment by jjjchens235** [comment]
You need to run it outside of python.

**Comment by jawdropper16** [comment]
Wdym outside of python like what do i use?
