### ISSUE TITLE
You need to run it outside of python.

### ISSUE THREAD

**Issue by jawdropper16** [jjjchens235/bing-rewards#276]
You need to run it outside of python.

Edit: please re-open if this doesn't fix your issue

_Originally posted by @jjjchens235 in https://github.com/jjjchens235/bing-rewards/issues/275#issuecomment-1243048366_

It dont work
(and by the way I have no experience with github)

**Comment by jjjchens235** [comment]
please provide screenshots, or explain what you did

**Comment by jawdropper16** [comment]
in step 2 you had to install python 3, which I did
and then in step 3, you had to do BingRewards/requirements.txt
but you didnt say where or what program to do it in and I assumed you do it python which didnt work.
So If you can tell me what program you used or what didnt work that would be nice.
Because it has been 3 hours and I can't figure anything out

**Comment by jjjchens235** [comment]
1. If you're running windows, open 'command prompt', if you're using mac, open 'terminal'
2. navigate to the directory where you saved BingRewards (using `cd`). If you don't know what that is, google `cd linux command`
3. once you're in the directory that contains `requirements.txt`, run the `pip` command as you're doing now

**Comment by jawdropper16** [comment]
omg I have to remove the **Bingrewards** part in pip install -r **BingRewards**/requirements.txt

**Comment by jawdropper16** [comment]
so every time i run something i have to use cd in that directory?

**Comment by jawdropper16** [comment]
![image](https://user-images.githubusercontent.com/104870012/189551042-6a669786-9206-4d33-90ef-56846faeccec.png)

**Comment by jawdropper16** [comment]
thanks man, anyways do i even need VS code to do this?

**Comment by jjjchens235** [comment]
Nice! No vscode isnt necessary for this, unless you want to make changes to the code which shouldn't be necessary.

**Comment by jawdropper16** [comment]
Ok
