### ISSUE TITLE
ONLY US SUPPORTED

### ISSUE THREAD

**Issue by MootjeBorrelnootje** [jjjchens235/bing-rewards#278]
Yes, I understand that it's the only US supported, however, is there a way to force the US version of the site on a dutch IP? The bot works when I have a VPN on and doesn't without a VPN on. TYVM IN ADVANCE!

**Comment by MootjeBorrelnootje** [comment]
It has nothing to do with the dutch version of the site, it purely has to do with me being from the Netherlands. Whenever I turn off my VPN the daily set section of the site just fucking dissapears.

**Comment by Auncaughbove17** [comment]
It works for me and I'm in the netherlands.
Just set your display and preferred language to English US in your microsoft account settings, and set your rewards page to US, by scrolling to the bottom and selecting it. That works for me
![image](https://user-images.githubusercontent.com/26165288/197501040-619f4f71-e810-461b-87ec-27f7926a8a96.png)
