### ISSUE TITLE
update.sh

### ISSUE THREAD

**Issue by DimaRazb** [jjjchens235/bing-rewards#283]
Ola, I tried to update repo on Ubuntu and got an error:

user@vm:~$ /home/user/bing-rewards/update.sh
Updating 9333747..0c85507
error: Your local changes to the following files would be overwritten by merge:
        BingRewards/src/driver.py
Please commit your changes or stash them before you merge.
Aborting.

Fixed that by adding a line before git pull
**git stash**

The result after:
user@vm:~$ /home/user/bing-rewards/update.sh
Saved working directory and index state WIP on master: 9333747 changelog v1.13
Updating 9333747..0c85507
Fast-forward
 .dockerignore                    |  4 ++++
 setup.py => BingRewards/setup.py |  2 +-
 BingRewards/src/driver.py        |  8 +++++---
 BingRewards/src/rewards.py       |  6 ++++++
 CHANGELOG.md                     | 29 ++++++++++++++++++++++++++++-
 Dockerfile                       | 34 ++++++++++++++++++++++++++++++++++
 README.md                        | 27 ++++++++++++++++++++-------
 bing.cron                        | 26 ++++++++++++++++++++++++++
 compose.yaml                     | 16 ++++++++++++++++
 entry.sh                         | 24 ++++++++++++++++++++++++
 script.sh                        | 18 ++++++++++++++++++
 11 files changed, 182 insertions(+), 12 deletions(-)
 create mode 100644 .dockerignore
 rename setup.py => BingRewards/setup.py (98%)
 mode change 100755 => 100644
 create mode 100644 Dockerfile
 create mode 100644 bing.cron
 create mode 100644 compose.yaml
 create mode 100644 entry.sh
 create mode 100644 script.sh

**Comment by jjjchens235** [comment]
I'm pretty sure this is because you made some local changes to `driver.py`. Your error says: 
_error: Your local changes to the following files would be overwritten by merge:
BingRewards/src/driver.py_

If this isn't the case please feel free to re-open.
