### ISSUE TITLE
New User Interface

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#288]
MS changed the user interface with the new look and display of points.
As such, the only thing I see isn't working anymore is the point count.

**Comment by jjjchens235** [comment]
Are you in the USA, I don't see differences to the UI

**Comment by coollbv** [comment]
Yes, it the USA.
They just started changing it so not all the accounts are yet transferred to the new UI
https://www.reddit.com/r/MicrosoftRewards/comments/y2q1af/rewards_website_has_a_new_ui/

**Comment by malesci** [comment]
also in my case the UI for the visualization of the points has changed.
here last lines of the run where facing the issue:

```
> Error checking rewards status -
 Traceback (most recent call last):
  File "/home/runner/work/bing-rewards/bing-rewards/BingRewards/src/rewards.py", line 1245, in __print_stats
    days_to_bonus_str = self.driver.find_elements(
IndexError: list index out of range

['Sat, Oct 15 2022 08:14AM', 'Failed Offers']
```

**Comment by JourneyOver** [comment]
@malesci yea everyone is having the same issue if they are on the new UI, due to the fact that there are some small things missing in the header now like lifetime points, streak count and the x days until bonus gift.

Hopefully soon @jjjchens235 will be on the new UI as well, so that they can start working on fixing up these issues.

**Comment by jjjchens235** [comment]
I looked at the reddit thread and it looks like the new UI is a pilot program. No idea when the formal new UI will be rolled out, but until then I cannot develop on these changes.

**Comment by coollbv** [comment]
It seems it's not a big issue right now as everything seems to be working. Just poins, streak, etc. get messed up...

**Comment by JourneyOver** [comment]
also what is up with some offers being like:
```
       >> Trying NBA season opener
              >>> Checking cookies popup
              >>> No cookie popup present
              >>> Starting quiz
              >>> Multiple choice
              >>> Time out Exception
           << Failed to complete 'NBA season opener'
```

an a latest example? it's not a quiz, not multiple choice or anything. it's one you just click and let the page load to get the credit, from what I can tell this is even happening on the old UI as well.

**Comment by jigoop1** [comment]
@JourneyOver 
in rewards.py line # 1251
change to this
```
try: days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-counter-animation//span')[days_to_bonus_index].text
except: days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-daily-set-section/div/mee-rewards-streak/div/div[2]/mee-rich-paragraph/p').text
```
will give you  x days until bonus gift.

**Comment by JourneyOver** [comment]
@jigoop1 So I tried that and with that it instead throws this here:
```log
> Error checking rewards status -
 Traceback (most recent call last):
  File "/app/src/rewards.py", line 1252, in __print_stats
    days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-counter-animation//span')[days_to_bonus_index].text
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/rewards.py", line 1254, in __print_stats
    days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-daily-set-section/div/mee-rewards-streak/div/div[2]/mee-rich-paragraph/p').text
AttributeError: 'list' object has no attribute 'text'
```

even tried with `//mee-rewards-daily-set-section/div/mee-rewards-streak/div/div[2]/mee-rich-paragraph/p/b` instead and it also has the same issue:

```log
> Error checking rewards status -
 Traceback (most recent call last):
  File "/app/src/rewards.py", line 1252, in __print_stats
    days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-counter-animation//span')[days_to_bonus_index].text
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/src/rewards.py", line 1254, in __print_stats
    days_to_bonus_str = self.driver.find_elements(By.XPATH, '//mee-rewards-daily-set-section/div/mee-rewards-streak/div/div[2]/mee-rich-paragraph/p/b').text
AttributeError: 'list' object has no attribute 'text'
```

so sadly your solution doesn't seem to work either :/

**Comment by jigoop1** [comment]
just change to 
`days_to_bonus_str = self.driver.find_element(By.XPATH, '//mee-rewards-daily-set-section/div/mee-rewards-streak/div/div[2]/mee-rich-paragraph/p').text`

find_element not the find_elements i did typo.

**Comment by JourneyOver** [comment]
@jigoop1 Derp why I didn't I try that.. It works, no more errors for the `days_to_bonus_str` for now :D albeit my `Microsoft 'Points earned' today` thing is a bit off in the script for the test run I did xD says I earned 656 today when in reality I earned only 330 today but maybe tomorrow when the day resets it'll show the actual correct amount.

Now only other issue that really needs to be fixed is the issue pertaining to the offers that are just a click and load that doesn't have a quiz or multiple choice because currently they seem to come back as `Failed to complete {offer name}`

**Comment by JourneyOver** [comment]
Well back to say that the "earned today" bit is still wildley off.. From what I can tell this value doesn't actually exist anywhere and the script is pulling some arbituary number from `dailyPoint > pointProgress` in the html even though this number does not seem to actually match how many points you have actually gained for the day.. From the looks of things this is even an issue in the old UI as well..

So ontop of things like https://github.com/jjjchens235/bing-rewards/issues/288#issuecomment-1283174218 we also have the above bit.

Other than that though, the change that jig has suggested for the days_to_bonus_str bit seems to be working well so far.

**Comment by jhaugh0** [comment]
> Well back to say that the "earned today" bit is still wildly off (earned 300 but script says 626).. From what I can tell this value doesn't actually exist anywhere and the script is pulling some arbituary number from `dailyPoint > pointProgress` in the html even though this number does not seem to actually match how many points you have actually gained for the day.. From the looks of things this is even an issue in the old UI as well..

This has been an issue for awhile. I opened an issue about it awhile ago: https://github.com/jjjchens235/bing-rewards/issues/219

I briefly looked into fixing it myself then got sidetracked and forgot about it

**Comment by JourneyOver** [comment]
> > Well back to say that the "earned today" bit is still wildly off (earned 300 but script says 626).. From what I can tell this value doesn't actually exist anywhere and the script is pulling some arbituary number from `dailyPoint > pointProgress` in the html even though this number does not seem to actually match how many points you have actually gained for the day.. From the looks of things this is even an issue in the old UI as well..
> 
> This has been an issue for awhile. I opened an issue about it awhile ago: #219
> 
> I briefly looked into fixing it myself then got sidetracked and forgot about it

tbh I somehow missed that there was already an issue open about that exact thing xD

**Comment by coollbv** [comment]
So it seems the beta dashboard is no more - can anyone else who had it confirm the reversion back to the old dashboard?

**Comment by JourneyOver** [comment]
Yea I was reverted back to the old dashboard as well. Who knows how long this is going to last though, and they may end up bringing back the other one at some point fully for everyone.

**Comment by andrewdens** [comment]
As of today my account didn't get stats output and it was for a couple of days

**Comment by JourneyOver** [comment]
Looks like they changed the UI a bit again, but things still seem to be in working order.. Make sure you are on the latest version @andrewdens
