### ISSUE TITLE
Successful login, does not work afterwards

### ISSUE THREAD

**Issue by Lexxior** [jjjchens235/bing-rewards#291]
I tried it with my host machine and it did not work
Spun up several VMs (Windows and Linux), this is the output I get when I run the script

```
jeff@jeff-VirtualBox:~/Downloads$ python BingRewards/BingRewards.py

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Sat, Oct 15 2022 11:42AM', 'Failed Edge Search, Web Search, Mobile Search, Offers, Latest Punch Card Activity']

You selected remaining
       >> Logging in
           << Successfully logged in
Traceback (most recent call last):
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55e1eba192c3 <unknown>
#1 0x55e1eb82283a <unknown>
#2 0x55e1eb85b985 <unknown>
#3 0x55e1eb85bb61 <unknown>
#4 0x55e1eb893d14 <unknown>
#5 0x55e1eb879f6d <unknown>
#6 0x55e1eb891a50 <unknown>
#7 0x55e1eb879d63 <unknown>
#8 0x55e1eb84e7e3 <unknown>
#9 0x55e1eb84fa21 <unknown>
#10 0x55e1eba6718e <unknown>
#11 0x55e1eba6a622 <unknown>
#12 0x55e1eba4daae <unknown>
#13 0x55e1eba6b2a3 <unknown>
#14 0x55e1eba41ecf <unknown>
#15 0x55e1eba8b588 <unknown>
#16 0x55e1eba8b706 <unknown>
#17 0x55e1ebaa58b2 <unknown>
#18 0x7fcee10e0609 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55e1eba192c3 <unknown>
#1 0x55e1eb82283a <unknown>
#2 0x55e1eb85b985 <unknown>
#3 0x55e1eb85bb61 <unknown>
#4 0x55e1eb893d14 <unknown>
#5 0x55e1eb879f6d <unknown>
#6 0x55e1eb891a50 <unknown>
#7 0x55e1eb879d63 <unknown>
#8 0x55e1eb84e7e3 <unknown>
#9 0x55e1eb84fa21 <unknown>
#10 0x55e1eba6718e <unknown>
#11 0x55e1eba6a622 <unknown>
#12 0x55e1eba4daae <unknown>
#13 0x55e1eba6b2a3 <unknown>
#14 0x55e1eba41ecf <unknown>
#15 0x55e1eba8b588 <unknown>
#16 0x55e1eba8b706 <unknown>
#17 0x55e1ebaa58b2 <unknown>
#18 0x7fcee10e0609 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 226, in __open_dashboard
    raise(e)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55e1eba192c3 <unknown>
#1 0x55e1eb82283a <unknown>
#2 0x55e1eb85b985 <unknown>
#3 0x55e1eb85bb61 <unknown>
#4 0x55e1eb893d14 <unknown>
#5 0x55e1eb879f6d <unknown>
#6 0x55e1eb891a50 <unknown>
#7 0x55e1eb879d63 <unknown>
#8 0x55e1eb84e7e3 <unknown>
#9 0x55e1eb84fa21 <unknown>
#10 0x55e1eba6718e <unknown>
#11 0x55e1eba6a622 <unknown>
#12 0x55e1eba4daae <unknown>
#13 0x55e1eba6b2a3 <unknown>
#14 0x55e1eba41ecf <unknown>
#15 0x55e1eba8b588 <unknown>
#16 0x55e1eba8b706 <unknown>
#17 0x55e1ebaa58b2 <unknown>
#18 0x7fcee10e0609 <unknown>




```

**Comment by jjjchens235** [comment]
Can you please run with the following flags and report what the browser behavior is?
`python BingRewards/BingRewards.py -nsb -nhl`

**Comment by Lexxior** [comment]
It opens Chrome, logs in successfully, goes to rewards.microsoft.com, the page gets reloaded 2 times but nothing else happens and it stays on the rewards page

**Comment by jjjchens235** [comment]
I'm not sure honestly.  Are you in the USA?

The piece of code it's erroring out on is the following:
```
offer_xpath = '//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a'
```

Specifcally, it's trying to find the following web element in the home page `//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a`.

When I try to find the web element on the home page, it shows the first quiz:
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/19519336/197079654-64ef71b8-9f86-4ff0-9e1d-dd4c99938189.png">

Possible things you could try:
1. comment out the code  referenced by the error statement and try running it again:
```
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 223, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.presence_of_element_located((By.XPATH, offer_xpath)))

```
2. Is the web element `//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a` showing up in your home page? For the first offer, what is the element id, and how does it differ?

**Comment by Lexxior** [comment]
After commenting out the line it works now!
I just have to keep it running for a few days now to get to level 2 to unlock mobile searches

`jeff@jeff-VirtualBox:~/Downloads$ python BingRewards/BingRewards.py -nsb -nhl

Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=True, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

['Fri, Oct 21 2022 12:07PM', 'Failed Mobile Search, Offers']

You selected remaining
       >> Logging in
           << Successfully logged in
> Starting Mobile search
       >> Starting search
           << Account is 'LEVEL 1' - mobile searches not yet available.
    < Failed to complete Mobile search

> Starting Offers
       >> Logging in
           << Successfully logged in
> Error during Offers:
 Traceback (most recent call last):
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1294, in __complete_action
    completion = action(**action_kwargs)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1121, in __offers
    self.__perform_action_on_offers(self.__click_offer, daily_sets_xpath, [], offer_count=3)
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1096, in __perform_action_on_offers
    offer = self.driver.find_element(By.XPATH,
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 106, in find_element
    return self._dispatch("find", (by, value, self._driver), "find_element", (by, value))
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/support/event_firing_webdriver.py", line 118, in _dispatch
    result = getattr(self._driver, d_call)(*d_args)
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/jeff/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a"}
  (Session info: chrome=106.0.5249.119)
Stacktrace:
#0 0x5594986e02c3 <unknown>
#1 0x5594984e983a <unknown>
#2 0x559498522985 <unknown>
#3 0x559498522b61 <unknown>
#4 0x55949855ad14 <unknown>
#5 0x559498540f6d <unknown>
#6 0x559498558a50 <unknown>
#7 0x559498540d63 <unknown>
#8 0x5594985157e3 <unknown>
#9 0x559498516a21 <unknown>
#10 0x55949872e18e <unknown>
#11 0x559498731622 <unknown>
#12 0x559498714aae <unknown>
#13 0x5594987322a3 <unknown>
#14 0x559498708ecf <unknown>
#15 0x559498752588 <unknown>
#16 0x559498752706 <unknown>
#17 0x55949876c8b2 <unknown>
#18 0x7fef50f78609 <unknown>


> Error checking rewards status -
 Traceback (most recent call last):
  File "/home/jeff/Downloads/BingRewards/src/rewards.py", line 1239, in __print_stats
    streak_d = dashboard["streakBonusPromotions"][0]
IndexError: list index out of range


['Fri, Oct 21 2022 12:08PM', 'Failed Mobile Search, Offers']
jeff@jeff-VirtualBox:~/Downloads$


`
