### ISSUE TITLE
Discord and telegram notifications not working

### ISSUE THREAD

**Issue by andrewdens** [jjjchens235/bing-rewards#293]
I've got 3 different accounts setup and after updating to the latest version one of them isn't sending discord or telegram notifications and they are all setup the same way other than the email used.

**Comment by jhaugh0** [comment]
likely due to the new dashboard page being rolled out which breaks the stats output. see https://github.com/jjjchens235/bing-rewards/issues/288

**Comment by duronald** [comment]
Having the same issue. Stopped receiving notifications on 10-13-2022 but other than that everything works
