### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by CtrlValCanc** [jjjchens235/bing-rewards#298]
It was working fine until I formatted my pc. 
I tried manually downloading the latest chromedriver version and re-cloning the repo or manually downloading it from the releases. I don't get why it can't find the driver but with with `-d msedge.` (so edge drivers) it works fine.
Log attached.
[error.log](https://github.com/jjjchens235/bing-rewards/files/9956167/error.log)

**Comment by jjjchens235** [comment]
Why do you need to manually download the chromedriver?

Are you downloading the correct binary and saving it in the directory that the program expects it to be in?

**Comment by CtrlValCanc** [comment]
I manually downloaded it just in case the problem was with the "prebuilt" one. In both case it just doesn't work. I put it where the "stock" chrome driver is, in the "driver" folder

**Comment by jjjchens235** [comment]
Can you please do the following:
```sh
# delete current chromedriver
rm bing-rewards-master/BingRewards/drivers/chromedriver
python BingRewards/BingRewards.py -nhl
```

Please paste the full log console output, and report if the chrome browser opened or not.

**Comment by CtrlValCanc** [comment]
I'm sorry I didn't specify I'm on Windows. I tried with `del drivers/chromedriver` (from BingRewards folder), then I tried with `del drivers/chromedriver.exe` (suspecting you wanted me to delete this file) it just doesn't accept my input, it says "Option not valid-chromedriver[.exe]. 

If I run with -nhl it just doesn't open chrome browser, and this is the full log console output: 
`Command line options selected:
email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=False, cookies=False, nosandbox=False, telegram=False, discord=False, google_sheets=False, google_trends_geo=US

You selected remaining
Traceback (most recent call last):
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\src\driver.py", line 202, in get_driver
    driver = cls.WebDriverCls(driver_path, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__
    super().__init__(
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\valer\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        (No symbol) [0x009DE563]
        (No symbol) [0x00967FC1]
        (No symbol) [0x0085D04D]
        (No symbol) [0x0087A063]
        (No symbol) [0x008782E9]
        (No symbol) [0x008AF056]
        (No symbol) [0x008AEB2A]
        (No symbol) [0x008A8386]
        (No symbol) [0x0088163C]
        (No symbol) [0x0088269D]
        GetHandleVerifier [0x00C79B82+2658722]
        GetHandleVerifier [0x00C6CB84+2605476]
        GetHandleVerifier [0x00A8825A+620666]
        GetHandleVerifier [0x00A86E80+615584]
        (No symbol) [0x009705EC]
        (No symbol) [0x00975958]
        (No symbol) [0x00975A45]
        (No symbol) [0x0098050B]
        BaseThreadInitThunk [0x76157BA9+25]
        RtlInitializeExceptionChain [0x77C9BB9B+107]
        RtlClearBits [0x77C9BB1F+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\BingRewards.py", line 179, in <module>
    main()
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\src\rewards.py", line 1386, in complete_search_type
    self.__get_driver(device_type)
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\src\rewards.py", line 1273, in __get_driver
    self.driver = self.driver_factory.get_driver(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\valer\Documents\bing-rewards\BingRewards\src\driver.py", line 228, in get_driver
    raise WebDriverException(error_msg)
selenium.common.exceptions.WebDriverException: Message: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        (No symbol) [0x009DE563]
        (No symbol) [0x00967FC1]
        (No symbol) [0x0085D04D]
        (No symbol) [0x0087A063]
        (No symbol) [0x008782E9]
        (No symbol) [0x008AF056]
        (No symbol) [0x008AEB2A]
        (No symbol) [0x008A8386]
        (No symbol) [0x0088163C]
        (No symbol) [0x0088269D]
        GetHandleVerifier [0x00C79B82+2658722]
        GetHandleVerifier [0x00C6CB84+2605476]
        GetHandleVerifier [0x00A8825A+620666]
        GetHandleVerifier [0x00A86E80+615584]
        (No symbol) [0x009705EC]
        (No symbol) [0x00975958]
        (No symbol) [0x00975A45]
        (No symbol) [0x0098050B]
        BaseThreadInitThunk [0x76157BA9+25]
        RtlInitializeExceptionChain [0x77C9BB9B+107]
        RtlClearBits [0x77C9BB1F+191]
`

**Comment by jjjchens235** [comment]
I should have asked this first. Do you have the actual `Chrome` browser installed? If so, what version is it?

**Comment by CtrlValCanc** [comment]
Oh. I'm so damn dumb. I'm really sorry to have wasted your time. I formatted my pc and I didn't think about it. Thank you very mcuh and I'm really sorry.

**Comment by jjjchens235** [comment]
Happens to the best of us haha
