### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#308]
Started getting this:

> Error checking rewards status -
 Traceback (most recent call last):
  File "C:\msrw\bingrewards\src\rewards.py", line 1251, in __print_stats
    days_to_bonus_str = self.driver.find_elements(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

['Thu, Nov 17 2022 12:24PM', 'Failed Edge Search, Web Search, Mobile Search, Latest Punch Card Activity']

**Comment by ApEye** [comment]
Getting the same issues

`> Starting Mobile search
       >> Starting search
           << Account is 'LEVEL 1' - mobile searches not yet available.
    < Failed to complete Mobile search

> Error checking rewards status -
 Traceback (most recent call last):
  File "C:\Users\Tryst\Downloads\bing-rewards-1.15\bing-rewards-1.15\BingRewards\src\rewards.py", line 1251, in __print_stats
    days_to_bonus_str = self.driver.find_elements(
IndexError: list index out of range


['Mon, Nov 21 2022 01:36AM', 'Failed Mobile Search']`

![cmd_O3jE6AVYUB](https://user-images.githubusercontent.com/46307237/202982895-9c8f537f-f820-4d30-8d84-8617d4b17c34.png)

**Comment by sbaraka** [comment]
+1
