### ISSUE TITLE
Cant login Bug

### ISSUE THREAD

**Issue by badplay** [jjjchens235/bing-rewards#312]
hi i started with version 1.14 now updated via files to 1.15 but i get lot of bugs

Starting Offers
       >> Trying Pflanzen-Power voraus!
           << Already completed, or no points offered
       >> Trying Bonus Quiz
              >>> Checking cookies popup
              >>> No cookie popup present
           << Sign in Bing bug for offer 'Bonus Quiz', will try again
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer 'Bonus Quiz', will try again
       >> Trying Rewards-Umfrage des Tages
           << Sign in Bing bug for offer 'Rewards-Umfrage des Tages', will try again
       >> Trying Rewards-Umfrage des Tages
           << Sign in Bing bug for offer 'Rew

i only updated the files inside local machine should i do something else ??
Alsow looks like that it dosnt click on "login" at the search quiz side .. i mean not the frist login i mean the second one after logged in account version 1.14 have done this good

i have to tell that i use it in german

**Comment by jjjchens235** [comment]
There will be issues with non-USA offers, these are not supported.
