### ISSUE TITLE
Boo! Discord notification NOT sent, response code is: <Response [400]> with response msg `{"content": ["Must be 2000 or fewer in length."]}

### ISSUE THREAD

**Issue by amadeusgray** [jjjchens235/bing-rewards#315]
Output last lines:
 ```
          << Failed to complete 'Beginnen Sie mit der Tour'
       >> Trying Ziel festlegen
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete 'Ziel festlegen'
       >> Trying Quiz-Kaffeepause
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [####################          ] 2/3 (66%)              >>> Time out Exception
           << Failed to complete 'Quiz-Kaffeepause'
       >> Trying Bonus Quiz
**Boo! Discord notification NOT sent, response code is: <Response [400]> with response msg `{"content": ["Must be 2000 or fewer in length."]}`**
```

I think its because is giving a lot of errors, like "Failed to complete quiz 'Beginnen Sie mit der Tour'", for example, but i dont know why it fails, it makes every search, its only with quizzes

**Comment by jjjchens235** [comment]
Is this the full output of the console?

**Comment by amadeusgray** [comment]
This is the full one
```Boo! Discord notification NOT sent, response code is: <Response [400]> with response msg `{"content": ["Must be 2000 or fewer in length."]}`

Traceback (most recent call last):
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/a/bing-rewards2/BingRewards/BingRewards.py", line 179, in <module>
    main()
  File "/root/a/bing-rewards2/BingRewards/BingRewards.py", line 135, in main
    complete_search(rewards, completion, args.search_type, search_hist)
  File "/root/a/bing-rewards2/BingRewards/BingRewards.py", line 92, in complete_search
    rewards.complete_search_type(search_type, completion, search_hist)
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 1387, in complete_search_type
    init_points = self.__get_available_points()
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 1285, in __get_available_points
    return self.get_dashboard_data()['userStatus']['availablePoints']
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 240, in get_dashboard_data
    self.__open_dashboard()
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 227, in __open_dashboard
    self.__open_dashboard(try_count + 1)
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 226, in __open_dashboard
    raise(e)
  File "/root/a/bing-rewards2/BingRewards/src/rewards.py", line 210, in __open_dashboard
    WebDriverWait(self.driver, self.__WEB_DRIVER_WAIT_SHORT).until(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

```

**Comment by jjjchens235** [comment]
^This error is related to #317. Please pull down the new code and try re-running.

**Comment by amadeusgray** [comment]
Yeah, fixed, love u <3
Btw, i have a question, how can i make the docker image run every 8 hours for example and then stop the image and run it again 8 hours later?

**Comment by amadeusgray** [comment]
Also, is it normal that it dont complete like 40% of the quizzes it makes?
`       >> Trying Rewards-Umfrage des Tages
              >>> Starting quiz
           << Successfully completed 'Rewards-Umfrage des Tages'
       >> Trying Punkte sammeln
           << Already completed, or no points offered
       >> Trying Schneeflckchen, Weirckchen
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete 'Schneeflckchen, Weirckchen'
       >> Trying 3. Spieltag der Meisterschaft
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete '3. Spieltag der Meisterschaft'
       >> Trying Natur, soweit das Auge reicht
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete 'Natur, soweit das Auge reicht'
       >> Trying Gesundheit
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete 'Gesundheit'
       >> Trying Sammeln Sie mehr Rewards-Punkte auf dem Handy
`

**Comment by jjjchens235** [comment]
> Also, is it normal that it dont complete like 40% of the quizzes it makes?
> 
> ```
>   >> Trying Rewards-Umfrage des Tages
>               >>> Starting quiz
>            << Successfully completed 'Rewards-Umfrage des Tages'
>        >> Trying Punkte sammeln
>            << Already completed, or no points offered
>        >> Trying Schneeflckchen, Weirckchen
>               >>> Starting quiz
>                   <<< Could not detect quiz overlay
>               >>> Starting quiz2 (no overlay)
>               >>> Could not find quiz2 progress elements
>            << Failed to complete 'Schneeflckchen, Weirckchen'
>        >> Trying 3. Spieltag der Meisterschaft
>               >>> Starting quiz
>                   <<< Could not detect quiz overlay
>               >>> Starting quiz2 (no overlay)
>               >>> Could not find quiz2 progress elements
>            << Failed to complete '3. Spieltag der Meisterschaft'
>        >> Trying Natur, soweit das Auge reicht
>               >>> Starting quiz
>                   <<< Could not detect quiz overlay
>               >>> Starting quiz2 (no overlay)
>               >>> Could not find quiz2 progress elements
>            << Failed to complete 'Natur, soweit das Auge reicht'
>        >> Trying Gesundheit
>               >>> Starting quiz
>                   <<< Could not detect quiz overlay
>               >>> Starting quiz2 (no overlay)
>               >>> Could not find quiz2 progress elements
>            << Failed to complete 'Gesundheit'
>        >> Trying Sammeln Sie mehr Rewards-Punkte auf dem Handy
> ```

Non-USA offers don't always complete.

**Comment by jjjchens235** [comment]
> Yeah, fixed, love u <3 Btw, i have a question, how can i make the docker image run every 8 hours for example and then stop the image and run it again 8 hours later?

The `readme` has this blurb:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/19519336/205156869-d0e336e6-1575-42c3-b295-c3bb029360e9.png">
