### ISSUE TITLE
Excluding Geo and Langues Settings

### ISSUE THREAD

**Issue by badplay** [jjjchens235/bing-rewards#320]
Hi i am from Germany

and it works greate in my Country wenn i change US to DE in two GEO Tag Lines. But when we get a Update it will be overritten . So is there a way to exclude this setings in a config file or so ?

**Comment by jjjchens235** [comment]
- did you try this already ` python BingRewards.py -h`

```
  -gtg [GOOGLE_TRENDS_GEO], --google-trends-geo [GOOGLE_TRENDS_GEO]
                        two-letter country code to use for Google Trends API 'geo' argument. Please note: not all country codes are
                        supported by the API. Default is 'US'.
```

**Comment by badplay** [comment]
bingRewards\BingRewards.py -r -nhl -d chrome -gtg [US]

so like this right ?? or like
bingRewards\BingRewards.py -r -nhl -d chrome -gtg [US], --google-trends-geo [US]

**Comment by jjjchens235** [comment]
`python BingRewards.py -r -gtg DE`
