### ISSUE TITLE
Fails to run/open. Crashes instantly

### ISSUE THREAD

**Issue by Abel6669** [jjjchens235/bing-rewards#323]
> Chrome Update is Disabled but windows updated yesterday.
> 
> 
> There is nothing in the logs to say what is happening at all.
> 
> `PS D:\Users\*********\Documents\GitHub\bing-rewards\BingRewardsJP> python BingRewards.py -nsb
> 
> Command line options selected:
> email=None, search_type=remaining, driver=<class 'src.driver.ChromeDriverFactory'>, headless=True, cookies=False, nosandbox=True, telegram=False, discord=False, google_sheets=False, google_trends_geo=US
> 
> ['Thu, Dec 01 2022 12:45PM', 'Successful']
> 
> You selected remaining
> Remaining already completed
> 
> 
> ['Thu, Dec 01 2022 12:45PM', 'Successful']
> PS D:\Users\******\Documents\GitHub\bing-rewards\BingRewardsJP>

**### Seems deleting the LOGS folder and restarting the script works?**

**Comment by jjjchens235** [comment]
This is a feature not a bug, all **daily**  searches/offers were already completed so it will not run till the next day.
