### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by riahc3** [jjjchens235/bing-rewards#325]
Hello

You got code from various sources such as https://github.com/charlesbel/Microsoft-Rewards-Farmer and these allow multiple accounts. As much as this was forked, it would be nice to have this support multiple accounts

**Comment by deathart** [comment]
https://github.com/jjjchens235/bing-rewards/issues/34

**Comment by riahc3** [comment]
@deathart Right now, it even fails for single accounts (it doesnt do all the tests) so if it fails for one, I doubt it would work for various.

Also its hipocritical to say that the original author doesnt want it yet in one of the sources he based code off, it supports multiple accounts....

**Comment by badplay** [comment]
@riahc3 

it is working with multi acc i do it . check out https://github.com/jjjchens235/bing-rewards/issues/34#issuecomment-691410549

**Comment by Hawkadoodle** [comment]
lol its so simple to make minor adjustments to the base code to support multiple accounts yourself and as far as I know this was all his own work.

**Comment by jjjchens235** [comment]
> https://github.com/jjjchens235/bing-rewards/issues/34
> @riahc3 I just wanted to say that an Issue with the same title already exists :)
> 
> Moreover it is the deposit and the code of @jjjchens235 so if he does not want to dev the multiple account it is his right! of to say that it is hypocritical .... If this repository doesn't suit you, you have hundreds of others

@deathart - couldn't have said it better, closing as dup
