### ISSUE TITLE
cant use shopping for extra points

### ISSUE THREAD

**Issue by badplay** [jjjchens235/bing-rewards#329]
hi i use the bot outside usa i use the shortcut to change geo settings works good
but when it comes to shopping points it stops with message you shopping in usa and not in your country

is there a way too change that

**Comment by Lexxior** [comment]
login to the page on https://rewards.bing.com/ and claim manually

**Comment by jjjchens235** [comment]
I don't think so, unless you vpn it or something, but you risk ban
