### ISSUE TITLE
Failed to complete Edge and mobile searches

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#33]
I'm using the latest Chrome (version 85.0.4183.83) and chromedriver (version 85.0.4183.83).  Edge and mobile searches fail, with a caveat.  If I run the script multiple times, eventually Edge and mobile searches complete.  I'm guessing there have been changes made in the latest Chrome and chromedriver.  Has anyone else experienced this?

**Comment by jjjchens235** [comment]
Thank you for bringing this to my attention. I had to update the chrome user agents- everything should be working again.

**Comment by codenotworking** [comment]
Thanks for updating.  It works great.
