### ISSUE TITLE
Staying signed in with 2fa

### ISSUE THREAD

**Issue by gh0sti** [jjjchens235/bing-rewards#334]
Is there a setting to keep an account signed in with 2fa so I don't have to do the 2fa prompts each time? Is that the setting enabling cookies or does that do something else?

**Comment by jjjchens235** [comment]
No that's a Microsoft setting, if you have 2fa you will need to authenticate with 2fa each time - that's kind of the point.

The cookies setting allows you to skip the log in process if 2fa is turned off.

**Comment by gh0sti** [comment]
Fair enough thanks for the response.
