### ISSUE TITLE
Incomplete search

### ISSUE THREAD

**Issue by PubgStarz** [jjjchens235/bing-rewards#37]
Any idea why it would not complete all search? The script works fine for the quiz but not for the search always end up with this.

I use this for the action : BingRewards/BingRewards.py -r

![Screen Shot 2020-09-07 at 9 21 27 AM](https://user-images.githubusercontent.com/70452658/92392044-ad147000-f0eb-11ea-80f5-f7103853da3b.png)

Thanks!

**Comment by jjjchens235** [comment]
Could you post the error from error.log file?

**Comment by PubgStarz** [comment]
Tue, Sep 01 2020 09:50AM
> Starting Edge search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [                              ] 0/12 (0%)
           << Failed to complete search
    < Failed to complete edge search

> Summary
       >> Points earned: 45/2,777
       >> Streak count: 3 days
           << 5 days until bonus gift
       >> Available points: 80,623
> Starting web search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [                              ] 0/90 (0%)
           << Failed to complete search
    < Failed to complete web search

> Summary
       >> Points earned: 45/2,777
       >> Streak count: 3 days
           << 5 days until bonus gift
       >> Available points: 80,623
> Starting offers
       >> Logging in
           << Successfully logged in
       >> Trying Education quiz
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                    >>>> Progress: [                              ] 0/7 (0%)
                  <<< Failed to complete quiz2
           << Failed to complete Education quiz
       >> Trying Rewards coffee break quiz
           << Sign in Bing bug for offer Rewards coffee break quiz, will try again
       >> Trying Rewards coffee break quiz
           << Sign in Bing bug for offer Rewards coffee break quiz, will try again
       >> Trying Rewards coffee break quiz
           << Sign in Bing bug for offer Rewards coffee break quiz, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Daily poll
           << Sign in Bing bug for offer Daily poll, will try again
       >> Trying Games galore!
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                  <<< Failed to complete quiz2
           << Failed to complete Games galore!
       >> Trying Weather update
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                  <<< Failed to complete quiz2
           << Failed to complete Weather update
       >> Trying Set a goal
           << Already checked
       >> Trying Bonus quiz
           << Already checked
       >> Trying Daily poll
           << Already checked
    < Failed to complete offers

> Summary
       >> Points earned: 75/2,777
       >> Streak count: 3 days
           << 5 days until bonus gift
       >> Available points: 80,653
> Starting mobile search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [                              ] 0/60 (0%)
           << Failed to complete search
    < Failed to complete mobile search

> Summary
       >> Points earned: 84/2,777
       >> Streak count: 3 days
           << 5 days until bonus gift
       >> Available points: 80,662

**Comment by jjjchens235** [comment]
Are you in the United States? The points you get for each search type is different from mine (i.e. 60 possible points from mobile). In the past, this code has not worked for non-USA users.

**Comment by PubgStarz** [comment]
Canada here...

**Comment by codenotworking** [comment]
> Canada here...

Have you tried using VPN?

**Comment by jjjchens235** [comment]
> > Canada here...
> 
> Have you tried using VPN?

I would tread with caution, I remember researching that Bing is pretty good at detecting VPN's and will banl

**Comment by theflyingwombat** [comment]
I am getting the same issue and logs are close to the same as to what was pasted above.  I am in the US. Microsoft Edge bonus appears to be working but PC/Mobile are not working.

"failed to complete search"

**Comment by chris987789** [comment]
is this still an issue??
