### ISSUE TITLE
Lightspeed quiz failed to complete

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#38]
```
>> Trying Lightspeed quiz
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [######################        ] 3/4 (75%)
                  <<< Failed to complete quiz1 - tried every choice
           << Failed to complete Lightspeed quiz
```
Screenshot:
<img src="https://i.imgur.com/tF2OW09.png" width="250" />

**Comment by jjjchens235** [comment]
Thanks for pointing out.
I also got stuck on question 4 . I took a  look in non-headless mode, and for the last problem, it would not attempt any of the other answers except the first one.
For now, I think it's a bing bug, if it keeps acting up, let me know and I'll take a closer look.

**Comment by codenotworking** [comment]
Thanks for the update.

**Comment by codenotworking** [comment]
It seems the bug reappeared.
```
>> Trying Lightspeed quiz
              >>> Starting quiz
              >>> Multiple choice
                     >>>> Progress: [######################        ] 3/4 (75%)
                  <<< Failed to complete quiz1 - tried every choice
           << Failed to complete Lightspeed quiz
```
Took a screenshot of where it's stuck:
<img src="https://i.imgur.com/yWdCpEB.png" />

**Comment by jjjchens235** [comment]
Not an issue past few weeks, closing for now.
