### ISSUE TITLE
"Show what you know" quiz skipped

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#40]
```
>> Trying Show what you know
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                     >>>> Progress: [                              ] 0/5 (0%)
                  <<< Failed to complete quiz2
           << Failed to complete Show what you know
```
Screenshot:
<img src="https://i.imgur.com/uuzKQ9a.png" width="250" />

**Comment by jjjchens235** [comment]
Looks like I have the same issue. I went through the quiz and it looks like after clicking an answer (via selenium) and getting to the 'next question' page, the 'next button' is not clickable (even manually).

I think this is a case of Bing acting up, if this occurs still in a week or so, lmk and i'll look more closely.

**Comment by jjjchens235** [comment]
This quiz will appear in tomorrow's set. I believe the changes in quiz2() should take care of this. We shall see..

**Comment by codenotworking** [comment]
It seems like it worked.  Thanks.
```
>> Trying Show what you know
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                     >>>> Progress: [##############################] 5/5 (100%)
                  <<< Successfully completed quiz2
           << Successfully completed Show what you know
```
