### ISSUE TITLE
It ran for one day, now fails to complete any tasks.

### ISSUE THREAD

**Issue by CptanPanic** [jjjchens235/bing-rewards#42]
So I downloaded yesterday, and succesfully completed some rewards. Today I tried to run again, and nothing works. I did reach level 2 yesterday.  Any ideas how to debug?

Here is error I get when running '-r'

```
DevTools listening on ws://127.0.0.1:53892/devtools/browser/05a5b655-626b-4c25-ab2c-4e6bf7d8ebcc
       >> Logging in
           << Successfully logged in
       >> Starting search

Tue, Sep 22 2020 08:15AM
Traceback (most recent call last):
  File "BingRewards\BingRewards.py", line 95, in __main
  File "C:\Users\brian\Downloads\bing-rewards\BingRewards\src\rewards.py", line 865, in complete_edge_search
    driver = self.__complete_edge_search()
  File "C:\Users\brian\Downloads\bing-rewards\BingRewards\src\rewards.py", line 739, in __complete_edge_search
    self.completion.edge_search = self.__search(driver, Driver.WEB_DEVICE, is_edge_search)
  File "C:\Users\brian\Downloads\bing-rewards\BingRewards\src\rewards.py", line 198, in __search
    current_progress, complete_progress = self.__get_search_progress(driver, device, is_edge)
  File "C:\Users\brian\Downloads\bing-rewards\BingRewards\src\rewards.py", line 123, in __get_search_progress
    for element in progress_elements:
UnboundLocalError: local variable 'progress_elements' referenced before assignment
```

Here is result of '-o'

> Starting offers

```
DevTools listening on ws://127.0.0.1:53734/devtools/browser/e7d1f1af-d9d3-4827-b5bb-32700254ddac
       >> Logging in
           << Successfully logged in
    < Failed to complete offers

    Error checking rewards status -  local variable 'IS_LEVEL_TWO' referenced before assignment
```

**Comment by DimaRazb** [comment]
Hey, you need Level 2 for this task working.
'IS_LEVEL_TWO'

**Comment by CptanPanic** [comment]
> Hey, you need Level 2 for this task working.
> 'IS_LEVEL_TWO'

Yes I am already level 2. Also looking at the code, it looks like that error is https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L840 , if you look at the if check above it, if len(stats) doesn't equal 5 or 6 then IS_LEVEL_TWO will not be set first.

**Comment by CptanPanic** [comment]
Update: actually that is only for printing the stats, so only happens after operation fails.

**Comment by jjjchens235** [comment]
In ln 112, progress_elements was never set.
https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/rewards.py#L112

The reason why it's not set is because at this url "https://account.microsoft.com/rewards/pointsbreakdown", the progress element from ln 112 could not be found. 

There are a variety of reasons for this, maybe the username/pw combo you inputted is incorrect, you're in a different country than the USA and the web elements are different, etc.

If you could.. please edit BingRewards.py and change headless = True. See if the program makes it to this url 'https://account.microsoft.com/rewards/pointsbreakdown' before erring out.

**Comment by CptanPanic** [comment]
> I'm assuming you're in the US. If so, please follow step below:
> Please edit BingRewards.py and change headless = True. See if the program makes it to this url 'https://account.microsoft.com/rewards/pointsbreakdown' before erring out.

Yes I am in the US, but HEADLESS = true by default : https://github.com/jjjchens235/bing-rewards/blob/89f63d236c8945d05e93eb922e432bcc3d6cd071/BingRewards/BingRewards.py#L17  Or did you mean something else?

**Comment by jjjchens235** [comment]
Ah makes sense. I guess the easy fix would be turning it off?
Thanks for bringing this issue up btw, I am going to add some better error handling so that we can isolate the issue at the time of login.
