### ISSUE TITLE
"Grab a snack and get comfy" quiz failed

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#43]
```
>> Trying Grab a snack and get comfy
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
                     >>>> Progress: [########################      ] 8/10 (80%)
                  <<< Failed to complete quiz2
           << Failed to complete Grab a snack and get comfy
```
Screenshot:
<img src="https://i.imgur.com/hy5bnY2.png" width="250" />

I've noticed when trying to complete it manually on one of my accounts, the `Next question` button stopped functioning after question 9.  I had to refresh the page to re-load the JavaScript so the button would work again.  Microsoft, or whoever developed it, knows how to make a real shitty website.

**Comment by jjjchens235** [comment]
I have updated. Program will refresh() if 'next' button is not clickable for quiz2().
