### ISSUE TITLE
Probably should be a delay after loading stats page to get real stats.

### ISSUE THREAD

**Issue by CptanPanic** [jjjchens235/bing-rewards#46]
So if you go to the microsoft rewards page, and look up your status the values are not static, but they dynamically ramp up. Currently the print_stats function uses a WebDriverWait to wait for the element to show up, but for me the stats the script ends up showing are lower than the real values. It seems to work better for me to put a time.sleep(5) right after this and it gets the real values.

**Comment by jjjchens235** [comment]
Good point, I think this is something I adjusted for, and then forgotten...
I'll make sure this is included in the next commit.
