### ISSUE TITLE
Plaintext Creds

### ISSUE THREAD

**Issue by gimmx** [jjjchens235/bing-rewards#50]
I think it's intentionally misleading to say that credentials are not in plaintext, because they are. Encoded plaintext is essentially still plaintext. I'm not even sure why you go through the effort of encoding.

**Comment by jjjchens235** [comment]
What would you propose instead ?

**Comment by gimmx** [comment]
Remove the encoding and allow those that use this to assess the risk themselves instead of employing false sense of security.

**Comment by chris987789** [comment]
To me it just seems like an added level of security, if someone accessed your files they wouldn't see a human readable version of your password.

In regards to entering the password each time you could write a script on your system to run setup.py then BingRewards.py -r then empty the config file. a simple bat or shell script would work for any OS.

I don't see this being a future release as for most people they don't want human readable passwords stored in files on their computers.

Time to close this 'issue'??

**Comment by jjjchens235** [comment]
All fair points. 

I'm going to simply update the README to be more explicit that this is plain text. If they're not comfortable with that, they can use the --email --password command-line arguments. The updated README will be in the next push.
