### ISSUE TITLE
Possible to get xbox search credits also?

### ISSUE THREAD

**Issue by CptanPanic** [jjjchens235/bing-rewards#52]
I don't have a Xbox yet, but I think there are some bing search points that you can get for searching on a xbox also. I wonder if anyone can get the user agent for this, so we can fake out this browser also?

**Comment by jjjchens235** [comment]
I found this list of user agents and I added it to the most recent commit:
https://developers.whatismybrowser.com/useragents/explore/operating_platform/xbox-one/

I don't have an Xbox and so I can't activate this offer, but if you could test it out that would be great.
