### ISSUE TITLE
"Hot takes" quiz failed

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#54]
```
>> Trying Hot takes
              >>> Starting quiz
              >>> Multiple choice
              >>> Time out Exception
           << Failed to complete Hot takes
```
Screenshots:
<img src="https://i.imgur.com/ZCEdl5i.png" width="250" />

<img src="https://i.imgur.com/VG2t44I.png" />

**Comment by jjjchens235** [comment]
Can you repost if this issue comes back up? I don't see this on my list of quizzes anymore.

**Comment by codenotworking** [comment]
Okay.  There were about two more Hot Take quizzes in the past two weeks, after my original post.

**Comment by codenotworking** [comment]
Today was another Hot Takes quiz, with no success:
```
>> Trying Hot takes
              >>> Starting quiz
              >>> Multiple choice
              >>> Time out Exception
           << Failed to complete Hot takes
```

**Comment by jjjchens235** [comment]
I have a pretty good streak going so I'm assuming that my most recent update fixed this. Please re-open if not.

**Comment by CptanPanic** [comment]
Looks like my issue getting to 7 day streak is due to this error, and "Failed to complete Hot takes" #64 So I am still having the issue.

**Comment by ForceConstant** [comment]
Since this is still a problem can you reopen?

**Comment by jjjchens235** [comment]
@ForceConstant Sure.

I have a 17 day streak going, so I'm guessing Hot takes isn't a common quiz? If you guys see this quiz come up, please let me know, and I'll try to take a look at it ASAP.

**Comment by jjjchens235** [comment]
No one re-reported issues after I reopened. Closing again.
