### ISSUE TITLE
Updating Mobile User Agent

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#55]
```
> Starting mobile search

DevTools listening on ws://127.0.0.1:62023/devtools/browser/e502c47d-ed77-477c-8848-72c252547698
       >> Logging in
           << Successfully logged in
       >> Starting search
              >>> Progress: [###################           ] 65/100 (65%)
           << Failed to complete search
    < Failed to complete mobile search
```

The current `chromedriver.exe` version I have is `86.0.4240.22`.  But the current Mobile User Agent in `driver.py` is:
```
__MOBILE_USER_AGENT         = "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36 EdgA/45.7.2.5057"
```
I visited the website that is in the comments of [driver.py](https://github.com/jjjchens235/bing-rewards/blob/fc5d6e99e26aed8eed58c9e9b967e61886ce8ab6/BingRewards/src/driver.py#L27), which is [https://www.whatismybrowser.com/guides/the-latest-user-agent/edge](https://www.whatismybrowser.com/guides/the-latest-user-agent/edge), but the site cuts off much of the text for the latest user agents.

Is there a way I can update the Mobile User Agent myself?

**Comment by jjjchens235** [comment]
As usual, thanks for bringing this to my attention. I saw the other issues you raised and I will take a look at them when I have the chance.
To your current issue...
The text appears to be cut off, but if you highlight the line and copy it, it will include the full line.

I think the below should work:
>
    __WEB_USER_AGENT            = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Edg/86.0.622.63"
    __MOBILE_USER_AGENT         = "Mozilla/5.0 (Linux; Android 10; HD1913) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36 EdgA/45.9.4.5083"
>

**Comment by codenotworking** [comment]
Thanks.  I can't believe it was as simple as highlighting and copying multiple lines to get the full text.  I even checked the HTML source code and the full text is there.  I'll just code a script in Python, using `requests` and `BeautifulSoup` to scrape that information from now on.
