### ISSUE TITLE
Several Quizzes failing

### ISSUE THREAD

**Issue by raphalation** [jjjchens235/bing-rewards#56]
Is this a problem with everyone or just me?

>> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
       >> Trying Supersonic Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Supersonic Quiz
       >> Trying Lightspeed Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Lightspeed Quiz
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
    < Failed to complete offers

**Comment by jjjchens235** [comment]
Please re-open if this is still an issue, I suspect updating the web user agent fixed this.
