### ISSUE TITLE
Cannot enter password

### ISSUE THREAD

**Issue by Saileyy** [jjjchens235/bing-rewards#57]
When i run "setup.py" it lets me enter my email fine, but won't let me enter my password. I can press enter and it'll say "config file updated successfully" and automatically close.

**Comment by DimaRazb** [comment]
Hey Saileyy, 
just try to copy and paste your password into the window and hit "Enter" then.

**Comment by Saileyy** [comment]
Hi, thanks for the help, unfortunately it doesnt allow for pasting.
I can type my email fine but can't paste my password.

**Comment by AJayHubs** [comment]
If you copy the password and then right-click on the window where you want it pasted it will paste it and you can press enter. It won't display any characters or confirmation that you pasted anything, but it does.

**Comment by Saileyy** [comment]
I'll try that right now, thanks

**Comment by Saileyy** [comment]
Okay, I think it worked but when i try and of the commands (w, m, b, o, a, or r) it says failed and no searches or challenges are completed.

**Comment by DimaRazb** [comment]
From which country you are running this?

**Comment by Saileyy** [comment]
I'm in England.

**Comment by jjjchens235** [comment]
Two suggestions:
1. Please paste the output of errors.log  (BingRewards/logs/errors.log)
2. Inside of BingRewards.py on line 16 adjust the code to
`HEADLESS                   = True
`

This will let you see what the browser is doing, should give you an indication of where and possibly why it failed.

**Comment by Saileyy** [comment]
Okay, thank you for the suggestions, i'll paste the error log.
Line 16 of BingRewards was already set to `HEADLESS = True`

**Comment by jjjchens235** [comment]
Sorry I meant to say change the code to
`HEADLESS = True`

Now that you provided the log though I have a hypothesis. Do you have chrome installed? If so, can you tell me what version it is?

**Comment by Saileyy** [comment]
Okay, so this whole time i forgot i was using the browser Vivaldi, which whilse based of Chrome to the point it can use Chrome extensions, isn't actually Chrome. I always forget because it can use Chrome extensions so i always assume its just a fork and whatever applies to Chrome applies to Vivaldi. I downloaded the latest Chrome and most things are working except some challenges.
The three "daily set" are working as are the searches so i won't lose any streaks but some of the extra 30 and 10 point challenges aren't working. I'll try some fixes like restarting my laptop and maybe trying again tomorrow until i bother you again. When everything works smoothly i'll try and set it to automatically run once a day. 

Thanks again for all your help, i'll update this later

**Comment by Saileyy** [comment]
Okay, so update; it works but when I launch `BingRewards.py` and type `all` it will complete the PC searches, Edge Searches, one of the daily sets and three of the extra challenges.
I have to then do the other daily sets/extra challenges manually and open `BingRewards.py` a second time and run `mobile` and it will complete the mobile searches.

**Comment by jjjchens235** [comment]
I'm going to close this, the quizzes in England probably have a different layout than the ones in the USA.
