### ISSUE TITLE
2FA Breaks the program

### ISSUE THREAD

**Issue by chrissythedev** [jjjchens235/bing-rewards#58]
```
       >> Logging in
Traceback (most recent call last):
  File "D:\BingRewards\BingRewards\src\rewards.py", line 99, in __login
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.url_contains("https://account.microsoft.com/"))
  File "C:\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\BingRewards\BingRewards\BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "D:\BingRewards\BingRewards\BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "D:\BingRewards\BingRewards\src\rewards.py", line 907, in complete_all
    driver = self.__complete_edge_search()
  File "D:\BingRewards\BingRewards\src\rewards.py", line 752, in __complete_edge_search
    self.__login(driver)
  File "D:\BingRewards\BingRewards\src\rewards.py", line 105, in __login
    raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully
```

**Comment by dvpierce** [comment]
Can confirm.

**Comment by LeVraiRoiDHyrule** [comment]
Same issue here.

**Comment by tw15egan** [comment]
Same here

**Comment by jjjchens235** [comment]
Per this Selenium [doc](https://www.selenium.dev/documentation/en/worst_practices/two_factor_authentication/), Selenium automation does not work well with 2FA.

If you wish to use this script, 2FA needs to be disabled, it is extremely difficult to automate with 2FA.

**Comment by jjjchens235** [comment]
This seems like a pretty common issue, I'll re-open this and see if I can come up with some hacky fix in the upcoming weeks.

I'm imagining a workflow like so:
1. If 2FA is turned and user runs using headless mode, an error will be thrown `You have 2FA turned on, you must run the program with the no-headless flag, i.e python BingRewards -nhl`
2. If running with no-headless mode, and program reaches 2FA page
   1. wait for 30 seconds OR until the field has a 6 char string
   2. Submit the 6 char string

**Comment by Bahnschrift** [comment]
I just did some messing around and managed to get 2FA working headless on my PC, I don't know if this would be quite feasible for the main branch, but the general idea is that during setup the user is able to paste the OTP generator code (the one used by Authenticator apps such as Authy) which, at login, is used by the pyotp library to generate and enter the OTP.

Could be worth considering  a similar approach?

**Comment by jjjchens235** [comment]
What is the issue with the current 2FA implementation as it already works using headless?

**Comment by Bahnschrift** [comment]
I think I've got a bit confused here with the different 2FA options for microsoft accounts. I'm using 24A through a 3rd party authenticator app which generates 6-digit OTPs every 30 seconds based on the generator code given by Microsoft. I couldn't see any way to make an account using this authentication system work. Sorry if I've missed something.
