### ISSUE TITLE
Quizes Fail to start and Complete

### ISSUE THREAD

**Issue by nivibilla** [jjjchens235/bing-rewards#60]
As the title says, everything else works but the quizes fail to complete.

**Comment by nivibilla** [comment]
Sun, Jan 17 2021 12:11PM
> Starting Edge search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [##############################] 12/12 (100%)
           << Successfully completed search
    < Successfully completed edge search

> Starting web search
       >> Starting search
             >>> Progress: [##############################] 90/90 (100%)
           << Successfully completed search
    < Successfully completed web search

> Starting offers
       >> Trying Antarctica trivia
           << Already checked
       >> Trying Bellissimo!
           << Already checked
       >> Trying Esports fan
           << Already checked
       >> Trying Quiz time!
           << Already checked
       >> Trying Beautiful design
           << Already checked
       >> Trying Give with Bing
              >>> skipping quiz - assuming it offers no points
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
       >> Trying Supersonic Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Supersonic Quiz
       >> Trying Lightspeed Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Lightspeed Quiz
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
    < Failed to complete offers

> Starting mobile search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [##############################] 60/60 (100%)
           << Successfully completed search
    < Successfully completed mobile search

> Summary
       >> Points earned: 212/2,986
       >> Streak count: 1 day
           << 2 days until bonus gift
       >> Available points: 7,292

Sun, Jan 17 2021 12:37PM
> Starting offers
       >> Logging in
           << Successfully logged in
       >> Trying Antarctica trivia
           << Already checked
       >> Trying Bellissimo!
           << Already checked
       >> Trying Esports fan
           << Already checked
       >> Trying Quiz time!
           << Already checked
       >> Trying Beautiful design
           << Already checked
       >> Trying Give with Bing
              >>> skipping quiz - assuming it offers no points
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
       >> Trying Supersonic Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Supersonic Quiz
       >> Trying Lightspeed Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Lightspeed Quiz
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
    < Failed to complete offers

> Summary
       >> Points earned: 212/2,986
       >> Streak count: 1 day
           << 2 days until bonus gift
       >> Available points: 7,292

**Comment by nivibilla** [comment]
Sun, Jan 17 2021 12:11PM
> Starting Edge search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [##############################] 12/12 (100%)
           << Successfully completed search
    < Successfully completed edge search

> Starting web search
       >> Starting search
             >>> Progress: [##############################] 90/90 (100%)
           << Successfully completed search
    < Successfully completed web search

> Starting offers
       >> Trying Antarctica trivia
           << Already checked
       >> Trying Bellissimo!
           << Already checked
       >> Trying Esports fan
           << Already checked
       >> Trying Quiz time!
           << Already checked
       >> Trying Beautiful design
           << Already checked
       >> Trying Give with Bing
              >>> skipping quiz - assuming it offers no points
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
       >> Trying Supersonic Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Supersonic Quiz
       >> Trying Lightspeed Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Lightspeed Quiz
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
    < Failed to complete offers

> Starting mobile search
       >> Logging in
           << Successfully logged in
       >> Starting search
             >>> Progress: [##############################] 60/60 (100%)
           << Successfully completed search
    < Successfully completed mobile search

> Summary
       >> Points earned: 212/2,986
       >> Streak count: 1 day
           << 2 days until bonus gift
       >> Available points: 7,292

Sun, Jan 17 2021 12:37PM
> Starting offers
       >> Logging in
           << Successfully logged in
       >> Trying Antarctica trivia
           << Already checked
       >> Trying Bellissimo!
           << Already checked
       >> Trying Esports fan
           << Already checked
       >> Trying Quiz time!
           << Already checked
       >> Trying Beautiful design
           << Already checked
       >> Trying Give with Bing
              >>> skipping quiz - assuming it offers no points
       >> Trying Bonus Quiz
           << Sign in Bing bug for offer Bonus Quiz, will try again
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
       >> Trying Supersonic Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Supersonic Quiz
       >> Trying Lightspeed Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Lightspeed Quiz
       >> Trying Bonus Quiz
              >>> Starting quiz
                  <<< Failed to start quiz
           << Failed to complete Bonus Quiz
    < Failed to complete offers

> Summary
       >> Points earned: 212/2,986
       >> Streak count: 1 day
           << 2 days until bonus gift
       >> Available points: 7,292

Tue, Jan 19 2021 09:43AM
Traceback (most recent call last):
  File ".\BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 909, in complete_all
    self.__complete_offers(driver)
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 826, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 719, in __offers
    c = self.__click_offer(driver, offer, './div[2]/h3', './mee-rewards-points/div/div/span[1]', './div[2]/p', './div[3]/a/span/ng-transclude')
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 669, in __click_offer
    completed = self.__quiz2(driver)
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 548, in __quiz2
    driver.find_elements_by_class_name('wk_Circle')[random.randint(0,2)].click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 226, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="wk_Circle">...</span> is not clickable at point (192, 454). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: headless chrome=87.0.4280.141)


Tue, Jan 19 2021 09:50AM
Traceback (most recent call last):
  File ".\BingRewards.py", line 100, in __main
    rewards.complete_offers()
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 895, in complete_offers
    driver = self.__complete_offers()
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 826, in __complete_offers
    self.completion.offers = self.__offers(driver)
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 737, in __offers
    c = self.__click_offer(driver, offer, './div[2]/h3', './mee-rewards-points/div/div/span[1]', './div[2]/p', './div[3]/a/span/ng-transclude')
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 669, in __click_offer
    completed = self.__quiz2(driver)
  File "S:\Work\Rewards Bot\bing-rewards\BingRewards\src\rewards.py", line 548, in __quiz2
    driver.find_elements_by_class_name('wk_Circle')[random.randint(0,2)].click()
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 226, in click
    self._dispatch("click", (self._webelement, self._driver), "click", ())
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 294, in _dispatch
    raise e
  File "C:\Python38\lib\site-packages\selenium\webdriver\support\event_firing_webdriver.py", line 291, in _dispatch
    result = getattr(self._webelement, d_call)(*d_args)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 628, in _execute
    return self._parent.execute(command, params)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "C:\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <span class="wk_...ircle">C</span> is not clickable at point (193, 522). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: headless chrome=87.0.4280.141)

**Comment by connect-dots** [comment]
Same as nivibilla. Quizes haven't worked for me for quite some time probably ~ Nov 20. Searches are fine but quizzes either fail or error out as above. Happy to use it regardless, but the number of points you can achieve without quizzes is much reduced. Appreciate all the hard work that goes into maintaining this repo :+1:

**Comment by jjjchens235** [comment]
Thanks for bringing this to my attention.
My quizzes have been working fine, are you guys in the United States?
It looks like most of the quizzes nivbillia posted from the logs are different from the quizzes I've been getting with a few exceptions.

**Comment by connect-dots** [comment]
@jjjchens235 I'm in the UK. I don't know if that's the same region as you but I can send some logs tomorrow if it helps? I'll add the switch to run the quizzes when my Cron job runs tomorrow and as them to this call.

**Comment by jjjchens235** [comment]
I think the regional difference is the issue, as I'm in the United States.
