### ISSUE TITLE
New Error Started 02/09/21

### ISSUE THREAD

**Issue by SeeMoreCode** [jjjchens235/bing-rewards#61]
It appears while executing the script today I will successfully log in and possibly complete 1-3 searches but error before completion.
![New Error](https://user-images.githubusercontent.com/33968533/107365555-f574f700-6aaa-11eb-8481-9c4f9bccc9e2.png)

Is anyone else experiencing this?
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by connect-dots** [comment]
Yep I get the same today. 

Judging by the error it looks like MS have switched up the position of the elements so the xpath has changed causing it to bug out. Saying that my Python is about as good as my grasp of quantum mechanics (i.e. zero)

**Comment by SeeMoreCode** [comment]
I believe that after researching the issue is that the elements have not loaded by the time the script wants to check. So in the rewards.py file, I added a time.sleep(3) to allow the element to load.

![Screenshot](https://user-images.githubusercontent.com/33968533/107389914-337f1480-6ac5-11eb-8d93-589c706094d7.png)


I am still playing with if it needs the full 3 seconds but it's a working start that I can scale down as needed.

**Comment by jjjchens235** [comment]
Thanks for bringing this up, I'm almost certain it's a driver issue due to Chrome upgrading from 87-> 88.

I'll try to add a fix by tonight.

**Comment by jjjchens235** [comment]
I have updated driver code, if you still have issues, please re-open.
