### ISSUE TITLE
Not getting all points on This or That

### ISSUE THREAD

**Issue by frosDfurret** [jjjchens235/bing-rewards#63]
Noticed that on the quiz "This or That", not all points were being given.
![2021-02-19 18-39-45 - Window](https://user-images.githubusercontent.com/64030476/108580875-5a69f180-72e2-11eb-9e01-19cdf93ec5a0.png)
Unsure if this is just how the program works, or if it's something more complicated.

**Comment by jjjchens235** [comment]
It randomly picks an answer, you have 50% chance of getting it right, so on average you should get 25/50, you had some bad luck mate.
