### ISSUE TITLE
Only ever get to 6 day streak

### ISSUE THREAD

**Issue by CptanPanic** [jjjchens235/bing-rewards#64]
Does this happen for anyone else? For the last month or so, I see that I get to 6 day streak, but then next day it starts over. I have looked at status page on the 6th day, and don't see anything missing, so not sure why I am not getting credit for the day. But this has happened at least 4 times.  Any ideas?

**Comment by CptanPanic** [comment]
Looks like issue is with "Hot Takes"

**Comment by jjjchens235** [comment]
Thanks for pointing this out. I'll close this one and re-open the original ticket.
