### ISSUE TITLE
Not located in a valid market, even when I am

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jjjchens235/bing-rewards#65]
Hi,

Microsoft Rewards is available in my country (France) but when trying to use this script I have this error :

raise RuntimeError("Logged in, but user not located in a valid market (USA, UK).")
RuntimeError: Logged in, but user not located in a valid market (USA, UK).

What should I do to get it working ?
Thanks for any answer

**Comment by LeVraiRoiDHyrule** [comment]
Found the solution ! I had to add my market as valid markets
VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=FR-FR']

**Comment by jjjchens235** [comment]
Nice! I'll add france to the list in the next release.

**Comment by LeVraiRoiDHyrule** [comment]
Would there be a way to use your script without installing chrome ? I am not a chrome user and having a full browser just for this is a bit annoying. Would there be a way to integrate chromium into it so it could run as a standalone ?
