### ISSUE TITLE
Error : Did not log in successfully

### ISSUE THREAD

**Issue by StanonGithub** [jjjchens235/bing-rewards#68]
Hi
I don't know why but i always got the same error when i try to use this script.

Can someone help me with this ?
![Capture d’écran 2021-04-19 123513](https://user-images.githubusercontent.com/72921479/115223096-b9de5500-a10b-11eb-93ae-273b4d97ff9c.png)

**Comment by jjjchens235** [comment]
What country are you in? If not USA , that may be the issue.

Another tip:
Inside BingRewards.py, change HEADLESS = FALSE, and see what the browser is actually doing, plz report back

**Comment by StanonGithub** [comment]
I'm in France but i've added ( 'mkt=FR-FR' ) in valid markets.

Now with HEADLESS = false, i can see that it's always stuck here when he try to verify my identity (I'm already connected in this browser so idon't know why he do that ): 

![Capture d’écran 2021-05-04 174622_LI](https://user-images.githubusercontent.com/72921479/117031495-ed6ed100-ad00-11eb-8995-32c29fab49df.jpg)

**Comment by jjjchens235** [comment]
Did you do [step #5](https://github.com/jjjchens235/bing-rewards#getting-started) in the README?
That should fix identity issue.

If the code ends up working for France, plz let me know so I can add to valid market list.

**Comment by StanonGithub** [comment]
I just found the problem. It that the 2 step verification was activate on my account !
I desactivated it and now the code is working perfectly !

Thanks for the help !
