### ISSUE TITLE
All quizzes failing

### ISSUE THREAD

**Issue by chris987789** [jjjchens235/bing-rewards#71]
Hi, 

Any idea what I can check to try and debug this??

`       >> Trying Press play
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Press play
       >> Trying Learning a new language?
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Learning a new language?
       >> Trying New home in 2021
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete New home in 2021
       >> Trying Rain or shine?
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Rain or shine?
       >> Trying Give with Bing
              >>> skipping quiz - assuming it offers no points
       >> Trying Inclusion for all
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Inclusion for all
`

Using in headless mode, non question/poll I get the points from anyway because they only require opening the link but I get this everyday.

I am UK based however if I run the script through a US proxy first it completes the quizzes.

Is this an issue with the UK based rewards site or anything within the code I can test?

Thanks, Chris

**Comment by jjjchens235** [comment]
Hey Chris, 
UK offers a different set of quizzes, thus the web elements are going to be different. I think you would have to implement your own solution for that.

Regarding proxy, just fyi, my understanding is that Bing is pretty good about catching that, and they do ban.

Lastly, I noticed you closed the linux ticket, do u mind sharing the fix?

**Comment by chris987789** [comment]
Hi,

No problem I'll have a look, same id on the btoverlay so shouldn't be too difficult to work out.

I'll add the linux solution on the closed post and leave this open until I can work something add to add as a solution.

**Comment by jjjchens235** [comment]
sounds good, would be more than happy to merge

**Comment by chris987789** [comment]
Yeah will have a look over it tomorrow looking to setup my raspberry pi to just let it do it's thing.

FYI I don't usually use a proxy it was just for debugging between US and UK.

**Comment by chris987789** [comment]
Ok so think I've fixed the issue, going to check again later on a new account to ensure it works on the raspberry pi as well. 

Problem in UK is cookie laws even if you accept it will reshow every time a new device is initialised again.

I've got the element ID added output into log and got it working on my windows machine now. I'm hoping chromium will act exactly same as chrome when run with chromedriver but as it's running on server without GUI will just have to try it when I setup a new account.

If confirmed working I'll send the updated code to incorporate into the program :-)

**Comment by chris987789** [comment]
Quizzes working in UK:

Ok so confirmed working on all OS's 

need to add

            '#Check for cookies popup
            self.__sys_out("Checking cookies popup", 3)
            time.sleep(self.__WEB_DRIVER_WAIT_SHORT)
            try:
                WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.element_to_be_clickable((By.ID, "bnp_btn_accept"))).click()
                time.sleep(self.__WEB_DRIVER_WAIT_SHORT)
                self.__sys_out("cookie popup cleared", 3)
            except:
                self.__sys_out("No cookie popup present", 3)'

into /src/rewards.py @ line 657 (on mine although have made some small edits so could be different) Just after:
           `if not checked:
            details = offer.find_element_by_xpath(details_xpath).text

            offer.find_element_by_xpath(link_xpath).click()
            #driver.execute_script('''window.open("{0}","_blank");'''.format(offer.get_attribute("href")))
            driver.switch_to.window(driver.window_handles[-1])
            #self.__handle_alerts(driver)`


I've also added two more option arguments into /src/driver.py

`        options = webdriver.ChromeOptions()
        options.add_argument("--disable-extensions")
        options.add_argument("--window-size=1280,1024")
        options.add_argument("--log-level=3")
        options.add_argument("--disable-notifications")
        options.add_argument("disable-infobars")`

Don't know if they're making much difference but could help incase chromium update changes or bing pages change.

Appreciate ref in new update release :-)

**Comment by connect-dots** [comment]
I'm based in the UK and have also faced the same issues with quizzes not working. Will test your changes as soon as I can and report back. Either way, thanks for working on a solution

**Comment by chris987789** [comment]
Yeah let me know if you're not sure where to put the update aswell.

**Comment by jjjchens235** [comment]
This looks great Chris. Do you mind creating a pull request? Will make it easier to merge and I think that way you'll get contribution credit. In terms of ref in new release, could you give me an example of what that would look like, I want to do right by you.

I'll try to do some testing either this week/wknd just to make sure it doesn't effect current code.

**Comment by chris987789** [comment]
K created pull request, I've checked on win linux and RPi running ubuntu 18.04 (linux amdx86 and arch)

Currently working on both US and UK markets.
