### ISSUE TITLE
ToS Update Causing Crash Till Manual Fix

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#74]
If Microsoft has ToS or other types of policy changes, the popup that appears when logging in breaks this.
Simple fix by adding a check if the agree button is present, and if it is, click it.
[error.log](https://github.com/jjjchens235/bing-rewards/files/6489136/error.log)

**Comment by tw15egan** [comment]
@JartanFTW what changes did you make to resolve this error?

**Comment by jjjchens235** [comment]
Thanks for bringing this to my attention. It looks like once you accept the ToS the first time, this page no longer pops up.

Regardless, I have made a change to the code that will take care of this going forward.
