### ISSUE TITLE
Email/Password Arguments

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#75]
Please consider adding two optional arguments that contain the login email and password respectively. If there is already an email/password saved from the setup file, it will ignore them and use the passed in ones (will NOT overwrite the saved ones).

I personally don't actually need it, but others might find it convenient.

**Comment by jjjchens235** [comment]
This is a great idea! I'm assuming you mean as a command-line argument?

I currently don't have the bandwidth for this but can put it in my backlog. If anyone has an interest in implementing this, would be more than happy to merge.

**Comment by JartanFTW** [comment]
> This is a great idea! I'm assuming you mean as a command-line argument?
Yep, exactly what I meant.

**Comment by jjjchens235** [comment]
I have this feature finished, will try to release it next weekend after I push out a more urgent feature.

**Comment by jjjchens235** [comment]
This has been completed.
