### ISSUE TITLE
Quiz Score Inconsistency

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#81]
I have noticed that the script isn't scoring 100% on quizzes most of the time. Is this intentional, a bug, or something else?

![image](https://user-images.githubusercontent.com/66337180/125344289-17f29100-e325-11eb-9510-93e2719005ed.png)

**Comment by jjjchens235** [comment]
It has to guess on This or That. There's no way for it to know the correct answer.
