### ISSUE TITLE
[Feature Request] Add Microsoft Edge driver option

### ISSUE THREAD

**Issue by wizardpeter** [jjjchens235/bing-rewards#82]
Does this work in Microsoft Edge instead of chrome?

**Comment by jjjchens235** [comment]
Not currently. This is a great idea, I will see what type of work it would require to implement this and if it's do-able I'll add it to my list of features to implement. Thanks for bringing this up!

**Comment by wastingoctober** [comment]
I would love this feature too. I currently have a task to open chrome daily just to make sure that it's up-to-date, but I'd much prefer to not even have chrome installed anymore.

**Comment by jjjchens235** [comment]
Looked at this more. I still think this would be a useful feature but the thought of implementing this doesn't excite me in the slightest, so I'm not picking this up.

#### Suggested Dev implementation
- Create a parent driver class. 
- Have 2 child classes- chrome and Edge
