### ISSUE TITLE
Line 107 in __login

### ISSUE THREAD

**Issue by wizardpeter** [jjjchens235/bing-rewards#83]
I try to run the BingRewards.py script but it says this:  raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully. Help. I put in the correct credentials but it doesn't work

**Comment by jjjchens235** [comment]
For this line of [code](https://github.com/jjjchens235/bing-rewards/blob/2121539269389c1a679516b594b78a0e9ec441f5/BingRewards/BingRewards.py#L16),  please adjust to run HEADLESS = True

Once line is adjusted, you can see what is happening in the back-ground, please report back.

**Comment by jjjchens235** [comment]
Closing this out due to lack of response
