### ISSUE TITLE
Timeouts logging in

### ISSUE THREAD

**Issue by webdeck** [jjjchens235/bing-rewards#87]
This past week has been very unreliable with days where I continually get timeouts trying to login:

```
['Tue, Aug 24 2021 06:54AM', 'Failed Web Search, Mobile Search, Offers']

	You selected remaining

> Starting Edge search
       >> Logging in
Traceback (most recent call last):
  File "/src/bing-rewards/BingRewards/src/rewards.py", line 107, in __login
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.url_contains("https://account.microsoft.com/"))
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/bing-rewards/BingRewards/src/rewards.py", line 111, in __login
    WebDriverWait(driver, self.__WEB_DRIVER_WAIT_SHORT).until(EC.url_contains("https://account.live.com/tou"))
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/bing-rewards/BingRewards/BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "/src/bing-rewards/BingRewards/BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "/src/bing-rewards/BingRewards/src/rewards.py", line 948, in complete_all
    driver = self.__complete_edge_search()
  File "/src/bing-rewards/BingRewards/src/rewards.py", line 793, in __complete_edge_search
    self.__login(driver)
  File "/src/bing-rewards/BingRewards/src/rewards.py", line 114, in __login
    raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully
```

**Comment by LordFarhad** [comment]
Getting the same exception.

**Comment by jjjchens235** [comment]
Could you please run in `HEADLESS = False` and check which page it's failing on, i.e 'terms of usage page'?

**Comment by webdeck** [comment]
It seems to be failing on this page after it signs in: https://rewards.microsoft.com/welcome?idru=%2F%3Fredref%3Damc

![Screen Shot 2021-09-02 at 7 04 07 AM](https://user-images.githubusercontent.com/5542961/131858097-393a1a5f-a363-4a69-8b5f-92f833fa8225.png)

**Comment by webdeck** [comment]
Actually, this error was not the same issue I was reporting, instead it is the new issue others are reporting about offers failing.  #90

**Comment by jjjchens235** [comment]
Are you still facing this issue? If so can you run in headless  = False again and let me know what screen it's erroring out?

**Comment by patricksegfault** [comment]
I ran with headless = False as I was also running into this issue. For me it was because I added a Microsoft Authenticator to my account. It seems to get stuck on this

**Comment by TBosak** [comment]
I was timing out on sign-in options because MS prompts with "Sign in with GitHub" now if your account is linked...just a heads up in case you want to throw in a catch for this. CSS selector for div id 'credentialList' should get the options if they're presented.

Credentials options:
![image](https://user-images.githubusercontent.com/41713011/132605520-09c00e49-02c9-461f-a0ab-dda12a82d354.png)

Only way I could think to grab the password option is via innerText or the svg:
![image](https://user-images.githubusercontent.com/41713011/132605677-f5e0365d-40b8-49c9-8f07-0432710115e4.png)

**Comment by jjjchens235** [comment]
@TBosak 
Hey sorry for the late reply, that's a great suggestion.

Would you be able to provide the URL. Also do you see this page before or after the `stay signed in` page?

**Comment by jjjchens235** [comment]
Closing this out for now, github URL unknown currently.
