### ISSUE TITLE
No such element errors for 'Offers'

### ISSUE THREAD

**Issue by binarymelon** [jjjchens235/bing-rewards#92]
For the last few days I've been getting errors on the offers section.

```
> Starting offers
<class 'selenium.common.exceptions.NoSuchElementException'>
    < Failed to complete offers
```

**Comment by binarymelon** [comment]
It just looked like it was sitting on the rewards page.

**Comment by jjjchens235** [comment]
I think I have a fix for this, will release once I have a few days of success with it.

**Comment by jjjchens235** [comment]
This should be fixed now. Please reopen if issues still.
