### ISSUE TITLE
UnboundLocalError: local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by heximing** [jjjchens235/bing-rewards#93]
BingRewards.py is in this folder:
_C:\D\Python\bing-rewards-master\BingRewards_

Python.exe is in this folder:
_C:\D\Python\WPy64-38100\python-3.8.10.amd64_

_setup.py_ is OK. At the first run of _BingRewards.py_, it throws out a driver error as shown in the below picture and logs.
![20210910230525](https://user-images.githubusercontent.com/541861/132934240-ce5d9a1b-1d34-4ddc-93d5-4508c68b269a.jpg)

Fri, Sep 10 2021 11:04PM
Traceback (most recent call last):
  File "C:\D\Python\bing-rewards-master\BingRewards\BingRewards.py", line 92, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 962, in complete_all
    driver = self.__complete_edge_search()
  File "C:\D\Python\bing-rewards-master\BingRewards\src\rewards.py", line 806, in __complete_edge_search
    driver = Driver.get_driver(self.path, Driver.WEB_DEVICE, self.headless)
  File "C:\D\Python\bing-rewards-master\BingRewards\src\driver.py", line 118, in get_driver
    return EventFiringWebDriver(driver, EventListener())
UnboundLocalError: local variable 'driver' referenced before assignment

Nevertheless, the driver does successfully download, though. Running _BingRewards.py_ again the program will run correctly, as shown in the below picture:
![20210910230635](https://user-images.githubusercontent.com/541861/132934241-7c8489cd-afb1-4dc7-9a89-ac653f931ab7.jpg)

I thought _BingRewards/BingRewards.py_ has to be in the same folder of _pythong.exe_, so I copy BingRewards to here:
_C:\D\Python\WPy64-38100\python-3.8.10.amd64\BingRewards\BingRewards.py_
I deleted the driver and run it again. Same errors as above.

The good news is, as long as driver is present, the program will run correctly. No problem. So this could be a non-issue.

Python is not in PATH in the system. I use a portable python ([http://winpython.github.io]). I do not know if it makes a difference.

This computer does not have an IDE, so I run it in command line. I do not know if it makes a difference.

**Comment by jjjchens235** [comment]
The main issue is this 
`                        Tried downloading the 3
                        most recent chrome drivers. None match current Chrome browser version
`
The program thinks that your  chromedriver is not up to date with Chrome browser, so it tries to download a  different ver but never finds a matching one.

What version of Chrome do you have downloaded on your computer?

**Comment by jjjchens235** [comment]
I see the issue now, bottom line is you should be good, but you pointed out a flaw in the code I need to fix. Fixing now.

**Comment by jjjchens235** [comment]
This should be fixed.
