### ISSUE TITLE
how to run using non-headless?

### ISSUE THREAD

**Issue by Kavinda-Prabashwara** [jjjchens235/bing-rewards#94]
I tired -nhl for non-headless mode but it didnt work.
if I use -nhl I get a error such as _AssertionError_

**Comment by jjjchens235** [comment]
please post log, I am not able to reproduce this

**Comment by Kavinda-Prabashwara** [comment]
![image](https://user-images.githubusercontent.com/84891807/133060972-bceac239-19ed-4b72-bda4-63df53ad6e72.png)

Although I changed the variable HEADLESS to false and it worked but I want to use non-headless just in case

**Comment by jjjchens235** [comment]
I don't think you pulled in the most recent code

**Comment by Kavinda-Prabashwara** [comment]
oh yeah. thanks for your time 👍.
