### ISSUE TITLE
SSL Error when running

### ISSUE THREAD

**Issue by Aholicknight** [jjjchens235/bing-rewards#97]
![image](https://user-images.githubusercontent.com/7843719/134629688-4d725419-b3ee-484a-a2b9-9bc6d6bb450e.png)

For some reason when I run the python script, I am getting SSL errors. I am not using a VPN.

**Comment by Aholicknight** [comment]
Works now. If you set a custom user agent in chrome, the SSL errors will happen.

**Comment by Aholicknight** [comment]
Error is still happening

**Comment by jjjchens235** [comment]
Hi - sorry for the delayed response, per this [stackoverflow](https://stackoverflow.com/a/42340168), can you please add the following 2 lines of code
```py
options.add_argument('--ignore-certificate-errors')
options.add_argument('--ignore-ssl-errors')
```

to the driver.py [file](https://github.com/jjjchens235/bing-rewards/blob/master/BingRewards/src/driver.py#L109) ?

**Comment by jjjchens235** [comment]
@Aholicknight can you confirm this fixed the issue for you? If so, I can add the changes to master. Thanks.

**Comment by Aholicknight** [comment]
This was fixed a long time ago so I can't confirm. @jjjchens235
